### ISSUE TITLE
action: nothing/end.run_action(:create) examples?

### ISSUE THREAD

**Issue by jimhopp** [sethvargo/chefspec#107]
I'm trying to figure out a way to test resources that use the "action: nothing/end.run_action(:create)" pattern. I don't think they're currently testable with chefspec as chefspec expects "action :create".

Three questions:
1. Is my understanding correct?
2. Would it be possible to test these by writing specs against the state of the resources (rather than using the chefspec matchers)?
3. Is it feasible to add matchers for this pattern? If it is and someone can point me in the right direction I'm willing to take a crack at it.

Thanks.

**Comment by Poohblah** [comment]
Here's how I got this to work, in case anybody else (like me) comes across this issue trying to figure out how to test that your resource gets executed during compile phase.

`recipe/default.rb`:
```
rhsm_errata_level node['rhsm']['rhsm_errata_level'] do
  action(:nothing)
end.run_action(:install)
```

`spec/unit/recipe/default_spec.rb`:
```
    it 'applies the critical errata updates' do                                 
      rhsm_register = spy('RhsmCookbook::RhsmErrataLevel')                      
      expect(rhsm_register.to(receive(:run_action).with(:install)))             
      expect(chef_run).to install_rhsm_errata_level('critical')                 
    end
```

**Comment by Poohblah** [comment]
In case anybody lands on this issue page in the future (like I did), this has now been addressed with the `.at_compile_time` chefspec feature.  This is documented in the README.
