### ISSUE TITLE
Mock include_recipe

### ISSUE THREAD

**Issue by phoolish** [sethvargo/chefspec#121]
I have several recipes that include other recipes.  I don't want all of them to run just the current recipe.  Is there anyway to mock the include_recipe resource?  In addition, is there anyway to mock the include_recipe resource while still having access to the attributes?

**Comment by atheiman** [comment]
newer rspec syntax:

```ruby
allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('some_cookbook::some_recipe')
```

If you want to ensure `include_recipe` called with the right recipes, but don't want to load the resources in the recipe that is included:

```ruby
before(:all) { @included_recipes = [] }
before do
  @stubbed_recipes = %w[test_cookbook::included_recipe apt]
  @stubbed_recipes.each do |r|
    allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).with(r) do
      @included_recipes << r
    end
  end
end

it 'includes the correct recipes' do
  chef_run
  expect(@included_recipes).to match_array(@stubbed_recipes)
end
```
