### ISSUE TITLE
Not able to mock cookbook libraries objects

### ISSUE THREAD

**Issue by allinwonder** [sethvargo/chefspec#138]
I am testing a recipe which is using a class I created in libraries folder. I want to stub a class method of it but failed. The real class is still being call after mocked. I don't know exactly why, my thinking maybe the issue happens related to module loading order. Please help

Please see the following code sample

> File: /cookbooks/example/libraries/myclass.rb

```
class MyClass
    def self.run_me
        puts 'i am real method'
    end
end
```

> File: /cookbooks/example/recipes/default.rb

```
MyClass.run_me
```

> File: /cookbooks/example/spec/default_spec.rb

```
require '/cookbooks/example/libraries/myclass.rb'
require 'chefspec'
describe 'example::default' do
    context 'when myclass is mocked' do
        before {
           MyClass.stub(:run_me) do
               puts 'I am a mocked method'
           end
        }
        it 'should print I am a mocked method' do
          chef_run = ChefSpec::ChefRunner.new
          chef_run.converge 'example::default'
        end
    end
end
```

> # bundle exec rspec

```
i am real method
.

Finished in 0.01377 seconds
1 example, 0 failures
```

**Comment by ramarnat** [comment]
How could I stub included methods from a library in a provider?

libraries/foo.rb
````
module Foo
  def correct?
    # check something
  end
end
````

provider/foo.rb
````
include Foo

action :blah do
  if check?
    # do something
  end
end
````

I have tried 
`allow_any_instance_of(Foo).to receive(:correct?).and_return(false)``

but it ignores the stub.

**Comment by ramarnat** [comment]
ok found the solution - https://github.com/sethvargo/chefspec/issues/562 
(although I had to use `allow_any_instance`

**Comment by paustin01** [comment]
@ramarnat I'm running into your exact issue.  Can you post what you did specifically?
