### ISSUE TITLE
stub_command for included recipes

### ISSUE THREAD

**Issue by fgimenez** [sethvargo/chefspec#260]
Hi, I have a recipe which is included by another one. In the included recipe there is a `not_if` guard, and in the corresponding spec the command is stubbed in a `before` block. But the spec for the including recipe complains about the unregistered command.

Any hints? 

Thanks, best regards

**Comment by brettcave** [comment]
@fgimenez - I was running into the same issue. commands stubbed in a `before do` weren't being stubbed.... however, moving them to a `before(:each) do` section successfully stubs the commands and works.

Not sure of underlying reason for this, or details of implementation, but HTH.

**Comment by bryandicarlo** [comment]
So this might not be the greatest thing to do, but it works.

>     before do
>       allow_any_instance_of(Chef::Resource::Conditional)
>         .to receive(:evaluate_command)
>         .and_return(true)
>     end
