### ISSUE TITLE
Stub Mixlib::ShellOut

### ISSUE THREAD

**Issue by till** [sethvargo/chefspec#264]
Been trying to wrap my head around stubbing mixlib::shellout in a cookbook. Any thoughts on where/how I would add this to chefspec? I'd work up a PR then.

**Comment by spuder** [comment]
For reference: Here is an example of this in motion:

https://github.com/juliandunn/library-demo-cookbook/blob/master/spec/unit/helper_spec.rb

Though it looks like it needs some updating for rspec 3

https://github.com/juliandunn/library-demo-cookbook/issues/2
