### ISSUE TITLE
question: testing action nothing

### ISSUE THREAD

**Issue by dpetzel** [sethvargo/chefspec#348]
I'm having some trouble getting a 100% touch rate. I have an execute resource which has an action of `:nothing` and I rely on a notification to trigger it. The command it generates is built using some node attributes, so I'd like to cover the resource via the `.with(command: /blah/`. The only way I got this to work (which I suspect is wrong) was to define my own match for `nothing_execute`. Here is what I have:

```
# spec/support/matchers.rb
def nothing_execute(resource_name)
  ChefSpec::Matchers::ResourceMatcher.new('execute', :nothing, resource_name)
end

# spec/recipes/my_spec.rb
expect(chef_run.package('my_package')).to notify(
  'execute[my_execute]').to(:run)
expect(chef_run).to nothing_execute('my_execute').with(
   command: /my_important_string/
 )
```

With only the notify check, it reports my execute resource as untouched. So even if I didn't want to check the command content, I still need to do _something_ to get it to be flagged as touched. So like I mentioned, I got this working with my custom matcher, but it feels like a hack and I suspect there is much better way to tackle this so hoping someone can educate me on a better approach

Thanks

**Comment by WarFox** [comment]
`to do_nothing` doesn't seem to work when expecting default action `:nothing` on the `service` resource.
Does it only work on explicitly declared action of `:nothing`? Is there a work around for this?

**Comment by WarFox** [comment]
I've got it working. It was my mistake.

This doesn't work
```
expect(chef_run).to do_nothing('service[my-service]')

     Failure/Error: expect(chef_run).to do_nothing('service[my-service]')

     ArgumentError:
       wrong number of arguments (1 for 0)
```

This doesn't work
```
expect('service[my-service]').to do_nothing

     Failure/Error: expect('service[my-service]').to do_nothing

     NoMethodError:
       undefined method `performed_actions' for "service[my-service]":String
```

And this works!
```
it 'expect service my-service to do nothing' do
    my_service = chef_run.service('my-service')
    expect(my_service).to do_nothing
end
```
