### ISSUE TITLE
Chef::Config[:client_key] being set to nil, breaks chef-client recipe

### ISSUE THREAD

**Issue by smedefind** [sethvargo/chefspec#364]
We ran into an issue when running ChefSpec against our base cookbook that includes running the chef-client cookbook.

chef-client::delete_validation runs `File.exists?(Chef::Config[:client_key])` to check for a client key. But since it is being set to nil inside of ChefSpec::Runner, it fails with the following error:

``` ruby
Failure/Error: ChefSpec::Runner.new(platform: platform, version: version, log_level: :error).converge(described_recipe)
     TypeError:
       can't convert nil into String
     # /var/folders/7m/p10c4zdx7v16x1_czkg80kw00000gp/T/d20140228-834-1s0yd2s/chef-client/recipes/delete_validation.rb:28:in `exists?'
     # /var/folders/7m/p10c4zdx7v16x1_czkg80kw00000gp/T/d20140228-834-1s0yd2s/chef-client/recipes/delete_validation.rb:28:in `block (2 levels) in from_file'
     # ./spec/default_spec.rb:8:in `block (5 levels) in <top (required)>'
     # ./spec/default_spec.rb:41:in `block (5 levels) in <top (required)>'
```

I found issue #237 that mentions this is being done on purpose to keep :search from breaking.

Stubbing out `include_recipe('chef-client::delete_validation')` to return true does allow ChefSpec to run, but then `expect(chef_run).to include_recipe('chef-client::delete_validation')` fails due to the recipe not showing up in the run_list (Separate bug?).

``` ruby
Failure/Error: expect(chef_run).to include_recipe('chef-client::delete_validation')
       expected ["base::chef-client", "chef-client::service", "chef-client::upstart_service", "chef-client::config"] to include "chef-client::delete_validation"
     # ./spec/chef-client_spec.rb:23:in `block (5 levels) in <top (required)>'
```

This can reproduced simply by adding `include_recipe chef-client::delete_validation` to a cookbook.

**Comment by jmauntel** [comment]
I'm having a similar issue.  Was this ever solved?

**Comment by gh2k** [comment]
For people who (like me) landed here from Google, here's how I fixed it on my setup:
```ruby
  let(:chef_run) do
    runner = ChefSpec::SoloRunner.new(platform: 'ubuntu', version: '14.04') do
      Chef::Config[:client_key] = "/etc/chef/client.pem"
    end
    runner.converge described_recipe
  end
```
