### ISSUE TITLE
It would be useful to be able to test the attributes of a Resource compiled to do :nothing

### ISSUE THREAD

**Issue by ghost** [sethvargo/chefspec#430]
It would be useful to be able to test the attributes of a resource with an initial action of :nothing.

**Comment by mfischer-zd** [comment]
There is a useful purpose for this functionality.  Some resources in recipes are never acted upon except via a notification.  Without this feature, there's no way to test whether the notified resource has the correct attributes.

I agree that there are other ways to test this, but a unit test would be mighty convenient.

**Comment by ranjib** [comment]
Did you check do_nothing matcher? That won't work?
