### ISSUE TITLE
Notification and declaration of service in different recipes

### ISSUE THREAD

**Issue by pniederlag** [sethvargo/chefspec#454]
Given I have two recipes:

``` ruby
# recipe_one.rb
service 'foo'
```

``` ruby
# recipe_two.rb
template '/this/template' do
  notifies :restart, 'service[foo]'
end
```

When I try to run ChefSpec on `recipe_two` to test my template resource like this:

``` ruby
expect(chef_run).to render_file('/this/template').with_content('foo = bar')
```

I get:

``` text
resource template[/this/template] is configured to notify resource service[foo] with action restart, but service[foo] cannot be found in the resource collection.
```

Any clue on how to solve this would be very welcome.

**Comment by wenchma** [comment]
@sethvargo , include_recipe is the only one way to access to that resource ? this way will run the recipe_one, if I don't want to run it, how to do? 
Actually, it will be Ok if the two recipes in one run_list, it only report error in spec test.

**Comment by alexanderadam** [comment]
@wenchma you could [create pseudo services](http://stackoverflow.com/questions/29029152/how-to-create-a-dummy-resource-defined-in-another-recipe-without-including-the-o) for the spec. But I admit that this is not a beautiful solution though and therefore curious too whether @sethvargo has a better solution for this. :wink:

**Comment by paustin01** [comment]
I know this is old but came here wondering the same thing as @wenchma .  How can you include without executing?  Let's say I have some resource in recipe_one.rb (which needs to run first) that schedules a delayed notification of something in recipe_two.rb.  What's the right way to go about it? @sethvargo  Any help is appreciated.
