### ISSUE TITLE
Matcher for `Chef::Log.xxx`

### ISSUE THREAD

**Issue by tknerr** [sethvargo/chefspec#465]
Just noticed there is a `write_log` matcher for converge-time `log` resources:
https://github.com/sethvargo/chefspec/blob/master/examples/log/spec/write_spec.rb

Would it be possible to provide a matcher for the compile-time `Chef::Log.debug "..."` etc. as well?

**Comment by atheiman** [comment]
For anyone that gets tripped up on this like I did, here is a working example:

```ruby
# recipes/default.rb

Chef::Log.warn('some warning')
```

```ruby
# spec/default_spec.rb

describe 'test_cookbook::default' do
  let(:chef_run) do
    ChefSpec::ServerRunner.new(platform: 'centos', version: '6.6').converge(described_recipe)
  end

  it 'writes the log' do
    expect(Chef::Log).to receive(:warn).with('some warning')
    # remember that you actually have to call `chef_run` after setting the expect
    chef_run
  end
end
```

The key part I was forgetting is actually calling `chef_run` after setting the expectation... Here is the rspec output.

```
$ rspec

test_cookbook::default
  writes the log

Finished in 1.08 seconds (files took 1.46 seconds to load)
1 example, 0 failures
```
