### ISSUE TITLE
Custom matchers are not loaded when used through a wrapper cookbook

### ISSUE THREAD

**Issue by ajwdev** [sethvargo/chefspec#467]
I ran into this issue this morning and I'm not totally sure if I'm doing something wrong or if its a bug. I didn't see anything in the README about this and couldn't find any previous issues about this. Sorry for the noise if this has been previously addressed.

I'm hitting a case with Chefspec 4.x where I cannot use custom matchers from a cookbook that is being wrapped by another cookbook. As an example here is a wrapper cookbook of the community 'runit' cookbook. It doesn't do anything besides include the default runit recipe and is only for demonstrating the problem:

https://github.com/TheDude05/test_runit

Now in an application cookbook I depend on the "test_runit" cookbook which gives me access to the `runit_service` LWRP. Example:

https://github.com/TheDude05/test_app_runit

``` ruby
include_recipe 'test_runit'

runit_service 'foo' do
  action :enable
end
```

In my spec I have ...

``` ruby
require_relative 'spec_helper'

describe 'test_app_runit::default' do
  subject do
    ChefSpec::Runner.new do |node|
      node.set[:runit] = {}
    end.converge(described_recipe)
  end

  it { should include_recipe 'test_runit' }
  it { should enable_runit_service 'foo' }
end
```

However when I run the tests I get an "undefined method" exception.

```
[andrew source/test_app_runit](master)$ bundle exec rspec
zsh: correct 'rspec' to 'spec' [nyae]? n
.F

Failures:

  1) test_app_runit::default 
     Failure/Error: it { should enable_runit_service 'foo' }
     NoMethodError:
       undefined method `enable_runit_service' for #<RSpec::ExampleGroups::TestAppRunitDefault:0x0000010353a3a0>
     # ./spec/default_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.24743 seconds (files took 1.2 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/default_spec.rb:11 # test_app_runit::default 
```

Is this behavior expected or am I doing something wrong? If it is expected, do you any suggestions on handling these kind of scenarios? Worst case I could just re-implement the matchers in my wrapper cookbook but I'd really like to avoid doing that if possible.

_EDIT:_ Found a typo in my spec file. Fortunately (or unfortunantly) the result is the same

**Comment by gsaslis** [comment]
Just had the exact same issue @sethvargo with the ark cookbook (different version in github / supermarket)

Thanks dude
