### ISSUE TITLE
It takes over 10 seconds for the files to load when running rspec.

### ISSUE THREAD

**Issue by squaresurf** [sethvargo/chefspec#492]
Am I doing something wrong or does it take that long for a simple chefspec setup run? Is there any way I can speed up the loading of the files?

**Comment by Chili-Man** [comment]
I'm running into this issue. I'm running chefdk 0.4.0 and have ran `gem cleanup`  but it doesn't seem to help.  I've only written the skeleton for the tests but it still takes about 10 seconds to just load up chefspec. 

this is what I have in my `spec/spec_helper.rb` and this is only file I have under `spec` so far:
     
    require 'chefspec'
    require_relative '../libraries/storage.rb'

     RSpec.configure do |config|
       config.log_level = :info
       config.platform = 'ubuntu'
       config.version = '14.04'
     end

I've also ran :
 
    $ time ruby -e "require 'chefspec'"

      real	0m8.831s
      user	0m8.208s 
      sys	0m0.616s
 

I'm not sure why it's taking so long to load the gem.

**Comment by vaibhavatul47** [comment]
I'm also facing same issue of `files took 7.91seconds to load`. Following this thread, I used `gem cleanup`. Once it finished I re-ran test and it started complaining `gem <name> not found`. Looks like it somehow uninstalled some required gems too. So I had to re-run `bundle install`.
