### ISSUE TITLE
registry_key_exists? mocked but registry_value_exists? is not

### ISSUE THREAD

**Issue by Xoph** [sethvargo/chefspec#514]
I have the following guard which ChefSpec tries to evaluate without mocking out the registry_value_exists? method. registry_key_exists? is mocked when I have used it as a guard. Can I mock this somehow? 

```
registry_value_exists?(
            'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\InetStp',
            { :name => 'VersionString', :type => :string, :data => '.'}, 
            :machine)}
```

**Comment by fghxu** [comment]
I am having the same issue.but not sure how to resovle.
can you give a more detailed sample,  i.e. without the (...)    ?
