### ISSUE TITLE
specs involving Chef::Config[:file_cache_path] is broken

### ISSUE THREAD

**Issue by ranjib** [sethvargo/chefspec#520]
``` rb
# resource
file File.join(Chef::Config[:file_cache_path], 'foo') do
   ...
  action :create
end
# spec
expect(chef_run).to create_file File.join(Chef::Config[:file_cache_path], 'foo')
```

is borken, since chefspec SoloRunner resets the path as part of initialization.
@sethvargo what about passing this as argument, in absence of which fall back to the exiting tmp directory logic?

**Comment by wenchma** [comment]
@sethvargo I also specified this option file_cache_path like that:
REDHAT_OPTS = {
  :platform => 'redhat',
  :version => '6.5',
  :log_level => LOG_LEVEL,
  :file_cache_path => '/var/chef/cache'
}

and use it : let(:runner) { ChefSpec::SoloRunner.new(REDHAT_OPTS) }
my unit test still failed : expect(chef_run).to create_remote_file_if_missing('/var/chef/cache/rabbitmq-server-3.4.2-1.noarch.rpm')

1) rabbitmq::default creates a rabbitmq-server rpm in the cache path
     Failure/Error: expect(chef_run).to create_remote_file_if_missing('/var/chef/cache/rabbitmq-server-3.4.2-1.noarch.rpm')
       expected "remote_file[/var/chef/cache/rabbitmq-server-3.4.2-1.noarch.rpm]" with action :create_if_missing to be in Chef run. Other remote_file resources:
       
         remote_file[/tmp/d20150107-30154-69s5lu/rabbitmq-server-3.4.2-1.noarch.rpm]
        
     # ./spec/default_spec.rb:104:in `block (2 levels) in <top (required)>'

I am confused, can you help this ?

**Comment by sethvargo** [comment]
@wenchma what version of ChefSpec /cc @ranjib

**Comment by wenchma** [comment]
@sethvargo  
$ gem list | grep chefspec
chefspec (4.1.1, 4.0.0, 3.4.0)

there are multi versions, does it matter ?

**Comment by ranjib** [comment]
can you update chefspec to 4.2.0 ?

**Comment by rmoriz** [comment]
still failing with 4.4.0
