### ISSUE TITLE
ChefSpec should support Chef environments

### ISSUE THREAD

**Issue by dougireton** [sethvargo/chefspec#54]
I realize this may be because ChefSpec relies on Chef Solo and Chef Solo doesn't yet support environments but I thought I'd submit this issue anyway. This code doesn't work:

``` ruby
describe 'hosts_file::windows' do

  let(:chef_run) { ChefSpec::ChefRunner.new }

  it 'installs the Secure hosts file for Secure servers' do
    chef_run.node.automatic_attrs[:platform] = 'windows'
    chef_run.node['hosts_file'] = { 'name' => 'Secure' }

    # this has no effect
    chef_run.node[:chef_environment] = 'test'

    chef_run.converge 'hosts_file::windows'
    expect(chef_run).to create_cookbook_file WINDOWS_HOSTS_FILE
  end

end
```

**Comment by mcascone** [comment]
How do I change the name of the stubbed environment during the test run - to test behavior in differently-named environments?

**Comment by anujbiyani** [comment]
I imagine you just change `env.name 'staging'` to whatever environment you want (referencing the code sample posted by @DracoAter just above your comment).

**Comment by mcascone** [comment]
I want to test 2 or more environment names. How do I set it as shown in the issue, and then change it later in the spec? Changing 'env.name' in an example doesn't seem to work. 

Thanks, Max

**Comment by DracoAter** [comment]
Why would you like to change the environment name inside spec? In spec you should only check, if the resource is in right state. Also you do understand (don't you), that you have to reconverge the recipe if you change the environment, so it perfectly fits into just another context.

**Comment by anujbiyani** [comment]
> What I want to do is test 2 or more environment names in the same spec file

Just use a different context per environment and put the aforementioned code within each environment-specific context.

```ruby
let(:chef_run) do
  ChefSpec::ChefRunner.new do |node|
    env = Chef::Environment.new
    env.name environment # using a variable here so we can change it in other contexts
    node.stub(:chef_environment).and_return env.name
    Chef::Environment.stub(:load).and_return env
  end.converge 'cookbook::recipe'
end

context 'in staging' do
  let(:environment) { 'staging' } # change the environment set up above in let(:chef_run)
  
  it 'does something' do
    expect(chef_run).to be_truthy
  end
end

context 'in development' do
  let(:environment) { 'development' } # again change the environment set up above in let(:chef_run)
  
  it 'does something different' do
    expect(chef_run).not_to be_truthy
  end
end
```

**Comment by mcascone** [comment]
That works perfectly. In the process I found that `stub` is being deprecated in favor of the `allow` format. 

I ended up with this:
    
    describe 'cookbook::recipe_under_test' do
      let(:chef_run) do
        ChefSpec::ChefRunner.new do |node|
        env = Chef::Environment.new
        env.name environment # using a variable here so we can change it in other contexts
        allow(node).to receive(:chef_environment).and_return(env.name)
        allow(Chef::Environment).to receive(:load).and_return(env)
      end.converge 'cookbook::recipe'
    end

    context 'Anywhere' do
      let(:environment) { '_default' }
      # test environment-agnostic stuff
      # note no `end` here

        context 'Not Production' do 
          # don't need to set env as it carries over from the parent context
          # test expected behavior
        end
  
        context 'Production' do 
          # set environment for this context
          let(:environment) { 'production' }
          # test environment specific stuff
        end
      end
    end

**Comment by anujbiyani** [comment]
> In the process I found that `stub` is being deprecated in favor of the `allow` format.

Ah yeah, I forgot about that. Good catch!

**Comment by revanthreddy36** [comment]
@anujbiyani  and @mcascone Thank you this is of great help. Is there a way to mock the roles of the actual nodes. For example I have a recipe that runs only in QA environemnt and when the role of the node is xyz_role. How to verify this using the chefspec/rspec ? ? 
Thanks in advance :)
