### ISSUE TITLE
yank older gems? depsolver going back to 0.0.1

### ISSUE THREAD

**Issue by martinb3** [sethvargo/chefspec#548]
Hello! Since upgrading to chef 12 and ruby 2.1.5, today, I'm noticing bundler is solving my constraints for chefspec by using version 0.0.1, since it has no declared dependency on rspec.

e.g.:
```
$ grep chefspec Gemfile.lock 
    chefspec (0.0.1)
```

If I add `gem 'chefspec', '>= 4'` just to push it up to a version that depends on rspec, everything works. Would you consider yanking the version of chefspec (0.0.1) that doesn't depend on rspec, just to make the bundler depsolver avoid it? Thanks in advance!

**Comment by sethvargo** [comment]
@martinb3 no, I don't yank gems unless there is a security vuln. The proper thing to do is specify the version of the gem in your Gemfile. That's "the Ruby way".

**Comment by ranjib** [comment]
Just use bundle update chefspec. Yanking gems is bad as it might make some
other dependent gem non functional
