### ISSUE TITLE
Many warnings logged regarding already initialized constants from other cokbooks

### ISSUE THREAD

**Issue by mwrock** [sethvargo/chefspec#550]
I am testing an LWRP and test runs, although successful, return a minimalist novel repeating such warnings as:

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.0.alpha.2/lib/chef/provider/lwrp_base.rb:97: warning: already initialized constant Chef::Provider::CronD
```

This is just one example of many. This started happening fairly recently. I'm sorry that is so vauge but its really getting in the way of my ability to debug some tests. These go away if I remove:

```
require 'chefspec/berkshelf'
```
but then i obviously get other errors about missing cookbooks.

Is this a known issue or is there some obvious thing I might be missing?

**Comment by sethvargo** [comment]
What version of Chef? What version of Ruby? What version of ChefSpec?

I think Chef changed constant loading in Chef 12 (/cc @lamont-graquist) to chime in if he has time.

**Comment by lamont-granquist** [comment]
Yeah, it changed.  I don't know if it changed before 12.0.0.alpha.2 or not.  If you can test with 12.0.3 that'd be useful.  If not, it'd be best to wait around until ChefDK 0.4.0 was released that will only have Chef 12-latest.

**Comment by mwrock** [comment]
Its chefspec 4.2, ruby 2.1.0 an chef 12.0.0.alpha.2. Based on @lamont-granquist's comment I installed chef 12.0.3. That killed the warnings but also introduced some compatibility issues with my LWRP code and chef 12.0.3. 

Anyways, sounds like thats the answer to the warning spam and I'll just need to address the incompatibility issues.

Thanks!
