### ISSUE TITLE
chefspec-4.2.0 very slow

### ISSUE THREAD

**Issue by someara** [sethvargo/chefspec#551]
Hi.

I just upgraded to the latest ChefDK, which includes ChefSpec 4.2.0.

After doing a string-replace to switch everything over to SoloRunner, rspec now takes ~12 minutes to complete on the mysql cookbook, vs the 2-3 from before.

https://gist.github.com/someara/85bea12a3651064c0bf9

Is there a way I should restructure the tests?

I'm looking to find a pattern for full test coverage of LWRPs that people can cargo-cult, and start banging the pans about it.

-s

**Comment by sethvargo** [comment]
Can you run the tests with `--profile` and find the slow ones?

**Comment by someara** [comment]
I sure can. https://gist.github.com/someara/61ea0d38eb74a6c1015a

**Comment by sethvargo** [comment]
So, my first instinct is that it has something to do with the Chef 12 changes to the way LWRPs are loaded. What if you cache the runner?

**Comment by someara** [comment]
It's running under Chef 11....

Chef Development Kit Version: 0.3.5
Chef: 11.18.0.rc.1
chefspec (4.2.0.beta.1)

I just tried upgrading chefspec/fauxhai, but no dice.

How do I cache the runner?

**Comment by someara** [comment]
I figured it out. Looks like we have a winner.

sed -i '' 's/let(/cached(/' *

laptop:~/src/opscode-cookbooks/mysql$ time chef exec /opt/chefdk/embedded/bin/rspec --profile
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 17.52 seconds (files took 3.23 seconds to load)
1937 examples, 0 failures

Top 10 slowest examples (2.1 seconds, 12.0% of total time):
  mysql_service_test::multi on omnios-151006 compiling the test recipe creates user[alice]
    0.22983 seconds ./spec/mysql_service/illumos/omnios_151006_service_55_multi_spec.rb:32
  mysql_service_test::single on centos-7.0 compiling the test recipe creates user[alice]
    0.21558 seconds ./spec/mysql_service/rhel/centos_70_service_57_multi_spec.rb:31
  mysql_service_test::single on centos-7.0 compiling the test recipe creates user[alice]
    0.21541 seconds ./spec/mysql_service/rhel/centos_70_service_56_multi_spec.rb:31
  mysql_service_test::single on smartos-5.11 compiling the test recipe creates mysql_service[default]
    0.21537 seconds ./spec/mysql_service/illumos/smartos_511_service_55_single_spec.rb:20
  mysql_service_test::single on ubuntu-14.04 compiling the test recipe creates user[alice]
    0.21236 seconds ./spec/mysql_service/debian/ubuntu_1404_service_56_multi_spec.rb:31
  mysql_service_test::single on smartos-5.11 compiling the test recipe creates mysql_service[default]
    0.20979 seconds ./spec/mysql_service/illumos/smartos_511_service_56_single_spec.rb:20
  mysql_service_test::single on ubuntu-10.04 compiling the test recipe creates user[alice]
    0.20863 seconds ./spec/mysql_service/debian/ubuntu_1004_service_51_multi_spec.rb:31
  mysql_service_test::single on centos-6.5 compiling the test recipe creates user[alice]
    0.20391 seconds ./spec/mysql_service/rhel/centos_65_service_57_multi_spec.rb:31
  mysql_service_test::single on centos-7.0 compiling the test recipe creates mysql_service[default]
    0.19971 seconds ./spec/mysql_service/rhel/centos_70_service_55_single_spec.rb:20
  mysql_service_test::single on fedora-20 compiling the test recipe creates mysql_service[default]
    0.19308 seconds ./spec/mysql_service/rhel/fedora_20_service_55_single_spec.rb:20

Top 10 slowest example groups:
  mysql_client_test::default on smartos-511
    0.07378 seconds average (0.14755 seconds / 2 examples) ./spec/mysql_client/illumos/smartos_511_client_55_spec.rb:3
  mysql_client_test::default on omnios-151006
    0.0734 seconds average (0.1468 seconds / 2 examples) ./spec/mysql_client/illumos/omnios_151006_client_55_spec.rb:3
  mysql_client_test::default on suse-11.3
    0.0721 seconds average (0.14419 seconds / 2 examples) ./spec/mysql_client/rhel/suse_113_client_55_spec.rb:3
  mysql_client_test::default on smartos-511
    0.06968 seconds average (0.13936 seconds / 2 examples) ./spec/mysql_client/illumos/smartos_511_client_56_spec.rb:3
  mysql_client_test::default on centos-5.8
    0.06846 seconds average (0.13691 seconds / 2 examples) ./spec/mysql_client/rhel/centos_58_client_51_spec.rb:3
  mysql_client_test::default on omnios-151006
    0.0663 seconds average (0.13261 seconds / 2 examples) ./spec/mysql_client/illumos/omnios_151006_client_56_spec.rb:3
  mysql_client_test::default on fedora-20
    0.05182 seconds average (0.15546 seconds / 3 examples) ./spec/mysql_client/rhel/fedora_20_client_57_spec.rb:3
  mysql_client_test::default on fedora-20
    0.04902 seconds average (0.14706 seconds / 3 examples) ./spec/mysql_client/rhel/fedora_20_client_55_spec.rb:3
  mysql_client_test::default on ubuntu-14.04
    0.04855 seconds average (0.14564 seconds / 3 examples) ./spec/mysql_client/debian/ubuntu_1404_client_55_spec.rb:3
  mysql_client_test::default on amazon-2014.09
    0.04848 seconds average (0.14544 seconds / 3 examples) ./spec/mysql_client/rhel/amazon_201409_client_57_spec.rb:3

ChefSpec Coverage report generated...

  Total Resources:   304
  Touched Resources: 304
  Touch Coverage:    100.0%

You are awesome and so is your test coverage! Have a fantastic day!


real	0m21.178s
user	0m19.023s
sys	0m2.125s

Thanks Seth!

-s

**Comment by sethvargo** [comment]
Look at that :smile:
