### ISSUE TITLE
Possible to stub service resource status?

### ISSUE THREAD

**Issue by daxgames** [sethvargo/chefspec#552]
I am using ChefDK 0.3.5.

Been trying to stub service resource status (started/running, stopped/not running), with and without custom status_command attributes, to direct cookbook flow in cases where this is necessary.  I have looked everywhere and not finding a lot.  Is this possible?

```ruby
            it "Stops service" do
              service = chef_run.service('Stop service')
              service.stub(:running).and_return(false)
              expect(chef_run).to stop_service('Stop service`')
            end
```
Any help is much appreciated.

**Comment by sethvargo** [comment]
What recipe are you trying to test?

**Comment by daxgames** [comment]
Actually I think I'm going to change the approach. Closing the issue.
