### ISSUE TITLE
Caching between test making tests order dependent

### ISSUE THREAD

**Issue by bytheway** [sethvargo/chefspec#555]
I've got a fairly large ChefSpec test suite that has become order dependent for a reason I can't yet explain.

The lwrp is a home-grown apache cookbook that accepts a vhost name, or defaults to the current node's hostname:

```ruby
attribute :vhost_name,  kind_of: String, default: lazy { node[:fqdn] }
```

This specific test suite sets automatic node attributes for every test run (not every spec does):

```ruby
let(:chef) do
  ChefSpec::SoloRunner.new(step_into: ['apache_instance']) do |node|
    node.automatic[:fqdn] = 'example.co.ihc.com'
    node.automatic[:hostname] = 'example'
  end
end
let(:chef_run) { chef.converge('apache::_test') }
let(:resource) { chef_run.find_resource('apache_instance', 'test') }
let(:provider) { Chef::Provider::ApacheInstance.new(resource, chef_run.run_context) }
```

We are also pulling out the resource, and creating an instance of the provider so that we can do some unit testing on provider methods.  

If I run just this one spec file alone, everything works fine, but if I run it while running the full suite, it seems the resource is getting its default from a previous node object.

Using pry (inside the provider) I dug in a little on the failing test:

```
[1] pry(#<Chef::Provider::ApacheInstance>)> node[:fqdn]
=> "example.co.ihc.com"
[2] pry(#<Chef::Provider::ApacheInstance>)> new_resource.vhost_name
=> "chefspec.local"
[3] pry(#<Chef::Provider::ApacheInstance>)> new_resource.node[:fqdn]
=> "example.co.ihc.com"
```

**Comment by sethvargo** [comment]
Hi @bytheway!

This is interesting. There are a few things I could see that might be causing this. Are you running Chef 12? Chef 12 refactored the way resource loading happened (/cc @lamont-granquist), and I'm wondering if the result from the `lazy` call is being cached on the resource in the LWRP.

Are these tests in different files/context blocks? Can you share some of the tests please?

**Comment by bytheway** [comment]
Chef 12.03
ChefSpec 4.2.0

I've tried defaulting with and without the lazy call, doesn't make any difference.

I have a number of different spec files, all with their own describe/context blocks.  If I run this file alone, in order, it is fine, it breaks if it is a randomized run that happens to be in a bad order, or if I run `rspec spec,` and have other specs run before it.

The test looks a bit strange for chefspec, because we are pulling out and testing some provider-level methods:

````
      it 'defines vhost_name as a String' do
        expect(provider.vhost_name).to be_nil
        provider.initialize_variables(true)
        expect(provider.vhost_name.class).to eq String
        expect(provider.vhost_name).to eq 'example.co.ihc.com'
      end
````

the initialize_variables method of the provider, is about what you'd expect:

```
def initialize_variables(stop=false)
  Chef::Log.debug("apache_instance LWRP: entering #{__method__} method")
  @group_name    = new_resource.group
  @flavors       = Array(new_resource.flavor)
  @master        = new_resource.master
  @slaves        = new_resource.slaves
  @ssl_enabled   = new_resource.ssl_enabled
  @vhost_name    = new_resource.vhost_name
  @vhost_aliases = new_resource.vhost_aliases
  @flavors      << "#{new_resource.flavor}_ssl" if ssl_enabled && new_resource.flavor !~ /_ssl$/

  # Sanity checks
  unless fqdn?(master)
    Chef::Log.warn("apache_instance LWRP: master (\"#{master}\") is not a FQDN")
  end

  Array(slaves).each do |slave|
    next if fqdn?(slave)
    Chef::Log.warn("apache_instance LWRP: slave (\"#{slave}\") is not a FQDN")
  end
end
````

**Comment by sethvargo** [comment]
Yea. I don't think Chef/ChefSpec is correctly unloading the constant between runs.

**Comment by lamont-granquist** [comment]
Yeah, we removed the unloading of Resource/Provider classes because that was awful for chef, and actually worse for chefspec's performance and memory leaks.

The correct way to fix this is not to use lazy like that.  Default it to nil in the resource and move that logic into the provider.  While we didn't have this in mind this use case was broken from a deliberate change and there's no fix I can see without reverting the behavior.

Lazy is a hack anyway that should never really be used.  Its a solution for being painted into a corner that  makes sure that you keep building enough infrastructure on top of that so that getting yourself out of the corner becomes intractable.  Lazy probably shouldn't have been added to the DSL.

**Comment by sethvargo** [comment]
@bytheway alternatively you could just move the LWRP into an HLWRP in libraries and name it as a real class I think.

**Comment by lamont-granquist** [comment]
That's an awful lot of work just to retain an anti-pattern.

**Comment by bytheway** [comment]
Makes sense.  I can work around it in the provider.

Before I saw this comment thread, I got together a cookbook demonstrating the issue. Available here:

https://github.com/bytheway/chefspec_bug

**Comment by sethvargo** [comment]
@bytheway if you could add a cucumber test (`features/`) that demonstrates the failure, I will be able to patch ChefSpec sooner.

**Comment by bytheway** [comment]
Seems kind of strange to have the ability to default a resource attribute, but have it be an anti-pattern to actually use it.  If I need to default resource attributes to a node attribute, I can certainly do a fallback in the provider, but it hides the fact that there is a default somewhat.

We end up needing to default a resource's attribute to something based on the node fairly regularly.

**Comment by bytheway** [comment]
Thanks @sethvargo, I'll work on getting that cookbook turned into a cucumber test.

**Comment by lamont-granquist** [comment]
'lazy' is the antipattern, it has all kinds of sharp edges.  seth, solving this problem and removing and redefining the class is going to get you right back to chef 11 LWRP issues again as well.
