### ISSUE TITLE
Improve control over the contents of a render_file matcher

### ISSUE THREAD

**Issue by miketheman** [sethvargo/chefspec#559]
This is a question, maybe I'm Doing It Wrong, but I've been poking at it for some time now, and can't seem to figure out if it's me or not.

In a recipe, I have a template resource that renders out a yaml file.

In a kitchen test, I am able to converge, inspect, load, convert the file to my liking - say load from yaml, convert to json and back, test validity of those operations.

Yes, I'm living on the edge.

I'd like to be able to use RSpec matchers to assert the validity of the rendered YAML file by converting it to JSON, and comparing the loaded object with an expected, dummy object - hopefully to catch any indentation errors I have.

The [json_spec](https://github.com/collectiveidea/json_spec) is the RSpec matcher I've been using successfully in Serverspec tests, so I wanted to see if I might be able to use i here as well in some fashion.

Consider, pseudo-code:
```ruby
expected = {
  "foo": "bar",
  "baz": [
    "qux",
    "quxx"
  ]
}

it 'renders a yaml file' do
  # yaml file:
  #   foo: "bar"
  #   baz: 
  #     - "qux"
  #     - "quxx"

  expect(chef_run).to render_file('/rendered.yaml').with_content(
   # manipulate the rendered content here to.json or such
    be_json_eql(expected.to_json)
  )
end
```

Or something along these lines.

The problem manifests that within `with_content()`, I will only have the raw YAML, and cannot manipulate that into something like `@content.to_json` for the purpose of comparison.

Does this make any sense?

**Comment by sethvargo** [comment]
Not currently possible, but I've been exploring yielding the rendered content:

```ruby
expect(chef_run).to render_file("whatevs").with_content do |content|
  # whatever you want in here
  expect(content).to match("foo")
  expect(JSON.parse(YAML.load(TOML.load(content))).to eq("panda")
end

Thoughts?
```

**Comment by miketheman** [comment]
@sethvargo I think that reads really cleanly - using the iterator for `content` follows how I would normally expect things to work - however the embedded `expects` make me wonder if that's something that would be surfaced back to rspec's output formatter?

Say `expect(JSON.parse(YAML.load(TOML.load(content))).to eq("panda")` fails - but the prior line passed - how would that be surfaced back to the user?

**Comment by sethvargo** [comment]
@miketheman it would just crash the same way a method would. The stacktrace would point to the spec. The spec would fail.

**Comment by miketheman** [comment]
@sethvargo Then that's awesome, I think. :grin:

**Comment by miketheman** [comment]
Hey @sethvargo wondering if anything came of this exploration? If you've got an "ideas" branch, I'd love to look at it and see if I can help at all.

**Comment by sethvargo** [comment]
I haven't had time to work on this

**Comment by miketheman** [comment]
Woot! I'll try and give this a test run soon. Thanks! :cake: :space_invader: :rotating_light:

**Comment by sethvargo** [comment]
Let me know how it goes, sorry for the delay.
