### ISSUE TITLE
Setting default node attributes to apply to every Runner

### ISSUE THREAD

**Issue by miketheman** [sethvargo/chefspec#560]
I find myself copying some node attributes that I expect to be located on every node during a given run.

I turn to thinking I might be able to put these into `spec_helper` style config, but it looks like there's a certain set of options that are allowed in there.
From:
https://github.com/sethvargo/chefspec/blob/f76b37784216899ce685049172e22d0e4b63a4e3/lib/chefspec/solo_runner.rb#L287-L308
https://github.com/sethvargo/chefspec/blob/f76b37784216899ce685049172e22d0e4b63a4e3/lib/chefspec/rspec.rb#L12-L19

Things like shimming in an EC2 node attribute, or other attributes that might be similarily used for all specs in a given group - without needing to update each spec file.

Am I looking in the wrong place?

**Comment by sethvargo** [comment]
Hey @miketheman,

You can just create any old Ruby method in your `spec_helper.rb`:

```ruby
def default_node_options
  {
    "..." => "...",
  }
end
```

And then use that hash when constructing the node object. You can also specify the JSON file where you can get data from. You can also pass an Fauxhai options directly into the `XRunner.new` call.

**Comment by miketheman** [comment]
Hey @sethvargo,
Thanks - don't know how I overlooked that. I guess I was thinking that there'd be some way to inject attributes via RSpec configuration helpers - the other methods work fine too.
