### ISSUE TITLE
Generating coverage report changes exit status of rspec command.

### ISSUE THREAD

**Issue by darklore** [sethvargo/chefspec#565]
I've found that exit status code is 0 if generating coverage report though there is some failures in spec.

ChefDK 0.4.0
chefspec 4.2.0

Reproduce procedure:
Prepare these files.
spec_helper
```ruby
require 'chefspec'
require 'chefspec/berkshelf'

ChefSpec::Coverage.start!
```

default_spec.rb
```ruby
require 'spec_helper'
describe 'test::default' do
  it 'should raise error' do
    expect{ChefSpec::ServerRunner.new.converge described_recipe}.to raise_error
  end
end
```

recipes/default.rb
```
(empty file)
```

And then run ```chef exec rspec```.
It reports 1 failure but exit status code is 0.

```
$ chef exec rspec
F

Failures:

  1) test::default converges successfully
     Failure/Error: expect{ChefSpec::ServerRunner.new.converge described_recipe}.to raise_error
       expected Exception but nothing was raised
     # ./spec/unit/recipes/default_spec.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.22133 seconds (files took 2.84 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/unit/recipes/default_spec.rb:11 # test::default converges successfully

  No Chef resources found, skipping coverage calculation...

$ echo $?
0
```

If remove ```ChefSpec::Coverage.start!``` from spec_helper.rb, the status code is 1.

Is it expected behavior that ```ChefSpec::Coverage.start!``` changes the exit status code to 0 though there is any failure in rspec run?

**Comment by sethvargo** [comment]
ChefSpec [captures the original error code from the RSpec run](https://github.com/sethvargo/chefspec/blob/a20f9c47077640292c3445752f6f2f56976f30e3/lib/chefspec/coverage.rb#L118-122), so it definitely should be maintaining the status.

**Comment by darklore** [comment]
Thank you for reply.

Original Simplecov code forces exit with the captured exit code only when it is not SUCCESS.
https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb#L82

Meanwhile, chefspec always exits with the captured code. And it is always SUCCESS when $! is nil.

**Comment by sethvargo** [comment]
@darklore look above... https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb#L44-L52

**Comment by darklore** [comment]
I see that same logic is used between chefspec and simplecov to capture error code from rspec run.
But there is a difference about the use of the error code when exit.
https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb#L82
https://github.com/sethvargo/chefspec/blob/v4.2.0/lib/chefspec/coverage.rb#L139

Simplecov exits with the error code when it is not SUCCESS, but chefspec always exits with the code.
This difference is intended?

**Comment by smedefind** [comment]
I've see this happen in OS X but not in our Jenkins environment which runs in Linux.

I haven't had a chance to debug it. So unfortunately I can't offer more than that as help.
