### ISSUE TITLE
The correct syntax for testing iis_section unlock

### ISSUE THREAD

**Issue by pvandervelde** [sethvargo/chefspec#568]
My cookbook installs and configures IIS by using the IIS cookbook (https://supermarket.chef.io/cookbooks/iis). The tests are failing because one of my test methods isn't recognized. I followed the chefspec documentation that says to write the test like so:

    expect(chef_run).to ACTION_RESOURCE(NAME)

Which in my case I think would mean

    expect(chef_run).to unlock_iis_section(SECTION_NAME)

So in my iis.rb recipe I have

    include_recipe 'windows'
    include_recipe 'iis'
    include_recipe 'iis::mod_aspnet45'
    include_recipe 'iis::mod_auth_windows'
    include_recipe 'iis::mod_logging'

    iis_section 'system.webServer/handlers' do
      section 'system.webServer/handlers'
      action :unlock
    end

And in my iis_spec.rb test file I have 

    before do
      allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).and_call_original
      allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('iis::default')
      allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('iis::mod_aspnet45')
      allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('iis::mod_auth_windows')
      allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('iis::mod_logging')
    end

    it 'includes the iis cookbook' do
      expect_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('iis::default')
      expect_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('iis::mod_aspnet45')
      expect_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('iis::mod_auth_windows')
      expect_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('iis::mod_logging')
      chef_run
    end

    it 'unlocks the system.webServer/handlers section' do
      expect(chef_run).to unlock_iis_section('system.webServer/handlers')
    end

But when I run the tests I get the following error

    nuget_server unlocks the system.webServer/handlers section
       Failure/Error: expect(chef_run).to unlock_iis_section('system.webServer/handlers')
       NoMethodError:
         undefined method `unlock_iis_section' for #    
    <RSpec::ExampleGroups::NugetServer_2:0x00000007268d90>
       # ./nuget_server/spec/iis_spec.rb:49:in `block (2 levels) in <top (required)>'

I'm sure there is an error in my cookbook or in my test but I'm not sure where it would be. Do I need to add some matcher from the IIS cookbook to my chefspec run or am I missing something else obvious?

**Comment by sethvargo** [comment]
ChefSpec only includes matchers for core Chef resources. Cookbooks that have their own resources need to [package customer matchers](https://github.com/sethvargo/chefspec#packaging-custom-matchers). I would recommend reaching out to the creators of that cookbook to have them package custom matchers in the iis cookbook so you can use them in your tests.

**Comment by pvandervelde** [comment]
Thanks I'll get in touch with the IIS cookbook developers.
