### ISSUE TITLE
Connection refused connecting to https://localhost/data

### ISSUE THREAD

**Issue by ror6ax** [sethvargo/chefspec#571]
Hi, 
When running rspec in cookbook directory, I get error as follows:
`[2015-03-05T13:15:42+01:00] ERROR: Connection refused connecting to https://localhost/data, retry 1/5`

Please advice.

**Comment by sethvargo** [comment]
Can you share any additional information? What does your spec_helper look like? What does your test look like? Can you run the command in debug mode and see if you get any output?

**Comment by ror6ax** [comment]
spec_helper:

```
# Added by ChefSpec
require 'chefspec'


RSpec.configure do |config|
   config.cookbook_path = '/home/ror6ax/chef/cookbooks/'
   config.log_level = :debug
end

```

test:

```
require_relative '../spec_helper'

describe 'clustering::default' do
  subject { ChefSpec::SoloRunner.new.converge('clustering') }

  let(:chef_run) { ChefSpec::SoloRunner.new.converge('clustering') }

  it 'installs ksh package' do
    chef_run.should install_package 'mksh-39-5.el6.x86_64.rpm'
  end

  it 'installs glibc package' do
     chef_run.should install_package 'glibc-2.12-1.107.el6_4.4.i686.rpm'
  end 
end

```

**Comment by sethvargo** [comment]
That is Chef making the external API call somewhere in your recipe. You should either use the `ServerRunner` or guard against Chef Solo in your recipes.
