### ISSUE TITLE
LWRP step_into with provides and extra conditions

### ISSUE THREAD

**Issue by biemond** [sethvargo/chefspec#580]
Hi, 

keep up the great work, really appreciated. 

I want to test my LWRP providers ( got multiple for different OS and file extensions ), step into my LWRP and test the chef resources. This works great when I use a simple provides with platform.  like this 

      provides :fmwjdk_jdk, os: 'windows'

But when I do something like this by adding an extra condition which is defined/set in the recipe

     provides :fmwjdk_jdk, os: 'linux' do |node|
        node['fmwjdk']['install_type'] == 'tar.gz'
     end

ChefSpec cannot detect the chef resources inside this LWRP. 

Do you know how to solve this or does this requires some modification to chefspec.

thanks again. 

Edwin

**Comment by sethvargo** [comment]
Hi @biemond 

I am not familiar with the `provides` when passed a block, but ChefSpec is just executing Chef under the hood. Can you verify your Chef recipes are working as expected on a real machine (perhaps using Test Kitchen)?

You will need to mock those node attributes, but it might be a catch-22 where the node attributes are mocked _after_ the LWRP is being loaded, thus the block is evaluating to false.

**Comment by biemond** [comment]
It is working fine in all test kitchen situations and on real VM's 
Do you have some examples or links how to mock those node attributes.  I will test the attributes mocking and let you know. 

Thanks Edwin

**Comment by sethvargo** [comment]
@biemond depending on how the loading is taking place, you may not be able to... There are some examples in the README for setting node attributes. If you share a test, I can provide some guidance.

**Comment by biemond** [comment]
already tried that by using node.set ( node['fmwjdk']['install_type'] = 'tar.gz' ) but that didn't make any difference.

    context 'With attributes, tar.gz on CentOS platform' do

      let(:chef_run) do
        runner = ChefSpec::ServerRunner.new(platform: 'centos', version: '6.6', step_into: ['fmwjdk_jdk_linux']) do |node|
          node.set['fmwjdk']['java_home_dir'] = '/usr/java/jdk1.8.0_40'
          node.set['fmwjdk']['source_file'] = '/software/jdk-8u40-linux-x64.tar.gz'
        end
        runner.converge(described_recipe)
      end

      it 'converges successfully' do
        expect(chef_run).to install_fmwjdk_jdk('/usr/java/jdk1.8.0_40')
        # expect(chef_run).to create_directory('/usr/java/jdk1.8.0_40')
      end

    end

I will make a testcase

**Comment by biemond** [comment]
Got it, 

very stupid

it was the java_home_dir exists check,  chef skipped the chef resources creation part inside the LWRP because java_home_dir was already there.

Thanks again.
