### ISSUE TITLE
Filter resources out of the coverage report if they aren't in the resource collection?

### ISSUE THREAD

**Issue by martinb3** [sethvargo/chefspec#581]
Hello! I have written a Chef provider that extends LWRPBase and declares some other resources within the provider's default action. I've used `step_into:` so that my provider is run during a chefspec run (and the resources it declares using the recipe DSL are created as a result).  As you've documented on the readme, ChefSpec isn't able to capture those resources and allow me to write rspec tests against those resources (the solorunner and serverrunner's resource_collection doesn't contain these resources). 

Due to the way chefspec captures instances of the Chef Resource class, and uses that to determine test coverage, it reports that my test coverage is less than 100%. Since I actually can't write a test against (they don't exist in ChefSpec's resource collection), would it make sense to filter those out of the coverage report?

If you'd like a concrete example, I'd be happy to provide; just let me know. Thanks in advance for your thoughts; I really appreciate it!

**Comment by sethvargo** [comment]
HI @martinb3 

If ChefSpec is reporting that the resources aren't covered, that means they are in ChefSpec's resource collection... Can you provide a concrete example?

**Comment by martinb3** [comment]
D'oh, I've since re-written it enough that I don't have the same example handy. It ended up being a class name interfering with a built-in chef class (I believe it was "search" :/). Please disregard... and thank you!
