### ISSUE TITLE
vagrant reload required to test updated local cookbook in config.vm.synced_folder ".", "/vagrant"

### ISSUE THREAD

**Issue by joelhandwell** [sethvargo/chefspec#588]
Hello, when I make change in `cookbooks/cookbook_name/recipes/recipe.rb`, it's applied in guest machine file system. But when I `vagrant ssh`, `cd /vagrant`, `bundle exec rspec /vagrant/spec/cookbook_name/recipe_spec.rb`, The updated cookbook is not tested by chefspec, but the older one is tested. When I do `cat /vagrant/cookbooks/cookbook_name/recipes/recipe.rb` the file is changed. But chefspec seems not recognized changed local cookbook **unless I run `vagrant reload` each time after modifing the cookbook**. And I tried to search around chefspec issues and Google, ended up not sure how I made it wrong. Is it chef & chefspec version mismatch? Or wrong config in spec_helper.rb? Wish to know if anybody have same problem and fixed it.

I have following development environment:

Host: Both in Windows 7 & OS X Yosemite (10.10)
VirtualBox: 4.3.26r98988
Vagrant: 1.7.2
Vagrant Box: Ubuntu 12

vagrant plugin list:
```
vagrant-berkshelf (4.0.3)
vagrant-cachier (1.2.0)
vagrant-ohai (0.1.11)
vagrant-share (1.1.3, system)
vagrant-vbguest (0.10.0)
```

Directory structure:
Vagrantfile
Gemfile
Berksfile
cookbooks/cookbook_name/metadata.rb
cookbooks/cookbook_name/recipes/recipe.rb
spec/spec_helper.rb
spec/cookbook_name/recipe_spec.rb

spec/spechelper.rb:
```Ruby
require 'chefspec'
require 'chefspec/berkshelf'
require 'mymatchers'

ChefSpec::Coverage.start! do
  add_filter(%r{/community_cookbook/})
end

RSpec.configure do |config|
  config.platform = 'ubuntu'
  config.version = '12.04'
  config.filter_run_excluding skip: true
end
```

vagrant ssh, ruby -v:
```
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

Gemfile:
```
source 'https://rubygems.org'
gem 'chef-zero'
gem 'chefspec'
...
```

Gemfile.lock:
```
...
berkshelf (3.2.3)
chef (12.2.1)
chef-zero (4.2.1)
chefspec (4.2.0)
ohai (8.2.0)
...
```

Berksfile
```
...
cookbook 'community_cookbook'
group :wrapper do
  cookbook 'cookbook_name', path: 'cookbooks/cookbook_name'
end
```

Vagrantfile
```
...
config.vm.synced_folder ".", "/vagrant" 
...

```

**update**
I also see many "warning: already initialized constant" as in https://github.com/sethvargo/chefspec/issues/550, and many "warning: previous definition of XXX was here" in this combination of chef, chefspec, and ruby.

**Comment by sethvargo** [comment]
What Vagrant plugins do you have installed? My suspicion is that, since you are using Berkshelf, you also have vagrant-berkshelf installed, which vendors cookbooks and the lockfile would force ChefSpec to use the vendor cookbook until a re-provision.

**Comment by joelhandwell** [comment]
I use following vagrant plugins, and yes it includes vagrant-berkshelf
vagrant-berkshelf (4.0.3)
vagrant-cachier (1.2.0)
vagrant-ohai (0.1.11)
vagrant-share (1.1.3, system)
vagrant-vbguest (0.10.0)

Is there any work around without uninstalling vagrant-berkshelf ?

**Comment by sethvargo** [comment]
@joelhandwell I think you can disable the vagrant-berkshelf plugin by saying `config.berkshelf.enabled = false` in the Vagrantfile.
