### ISSUE TITLE
uninitialized constant ChefSpec::SoloRunner

### ISSUE THREAD

**Issue by trekr5** [sethvargo/chefspec#591]
Hello,

I'm attempting to test a recipe using ChefSpec. I'm running my recipes on a Vagrant machine but each time I run my tests, I get the following error:-

```ruby
# install_spec.rb
require 'spec_helper'
require 'chefspec'

describe 'gg-ops-dashing::install' do 
  let(:chef_run) { ChefSpec::SoloRunner.converge('gg-ops-dashing::install') }	
  it 'installs ruby 1.9.3 package' do
    expect(chef_run).to install_package('ruby1.9.3')
  end	
end
```

```text
Failures:

  1) gg-ops-dashing::install installs ruby 1.9.3 package
     Failure/Error: let(:chef_run) { ChefSpec::SoloRunner.converge('gg-ops-dashing::install') }
     NameError:
       uninitialized constant ChefSpec::SoloRunner
     # ./spec/install_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/install_spec.rb:18:in `block (2 levels) in <top (required)>'

Finished in 0.00098 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/install_spec.rb:16 # gg-ops-dashing::install installs ruby 1.9.3 package.
```

I'm running Chef (11.16.4 x86-mingw32), chefspec 3.2 and ruby 1.9.3 on a Windows 8 machine.

**Comment by sethvargo** [comment]
Hi @trekr5 

The latest version of ChefSpec is 4.2.0, and the README corresponds to that released version:

> **This documentation corresponds to the master branch, which may be unreleased. Please check the README of the latest git tag or the gem's source for your version's documentation!**

Here is [the documentation for ChefSpec 3.2](https://github.com/sethvargo/chefspec/tree/v3.2.0). As you can see, ChefSpec 3 uses `ChefSpec::Runner` and does not differentiate between a solo and server runner.
