### ISSUE TITLE
apt_package and yum_package - support multiple package functionality

### ISSUE THREAD

**Issue by scotthain** [sethvargo/chefspec#592]
I'm not quite sure how to implement this, otherwise I'd toss in a PR, but it would be fantastic if chefspec could support this functionality - shown here: http://docs.chef.io/resource_package.html#multiple-packages

**Comment by ranjib** [comment]
@scotthain i can propose a workaround, till  this is fixed,
```ruby
package 'dependencies' do
   package_name %w(pkg1 pkg2 pkg3)
end
```
this will solve two things
1) you can test it using chefspec
```ruby
expect(chef_run).to install_package('dependencies').with(package_name: %w(pkg1 pkg2 pkg3))
```
2) chef run will not be cluttered due to the whole array being printed

**Comment by scotthain** [comment]
Thanks @ranjib - worked like a charm as a workaround!

**Comment by sethvargo** [comment]
I added tests for it in #617, but this works just as you'd expect already; no code change required.

**Comment by scotthain** [comment]
:+1: thanks @sethvargo!
