### ISSUE TITLE
Weird undefined method `[]` for nil:NilClass in ChefSpec

### ISSUE THREAD

**Issue by dgoradia-atlas** [sethvargo/chefspec#593]
recipes/default.rb
```
node.default['databag']['software'] = data_bag_item('software', 'insight')
```

recipes/file.rb
```
remote_path = "#{node['databag']['software']['source']['base_url']}/#{node['databag']['software']['source']['bucket']}"
```

When running rspec this throws of an error:
```
Failure/Error: end.converge(described_recipe)
     NoMethodError:
       undefined method `[]' for nil:NilClass
```

Oddly enough adding `node.default` works fine. Is this normal? I was under the impression that you only assign with `node.default` and use `node['...']` to use the attribute.
```
remote_path = "#{node.default['databag']['software']['source']['base_url']}/#{node['databag']['software']['source']['bucket']}"
```

**Comment by sethvargo** [comment]
You assign node attributes in attributes/default.rb, not recipes/default.rb.

**Comment by dgoradia-atlas** [comment]
I'm assigning the contents of a data bag item to the attribute so I can use it in multiple recipes which I include at the end of the default recipe. If I try to assign it in attributes/default.rb chefspec throws the error:
```
     Failure/Error: end.converge(described_recipe)
     NoMethodError:
       Undefined node attribute or method `data_bag_item' on `node'
```

**Comment by sethvargo** [comment]
Right, that's because you cannot load data bags from inside an attribute. You should not be loading data bags into attributes - it does not make sense.

**Comment by dgoradia-atlas** [comment]
It makes sense in my case where I need to pull in an attribute that is written in a json file (data bag item) by an external system. Are you saying that if I have a data bag item that I need to grab some data from, I must repeat its loading in each and every recipe that I need that data?

**Comment by sethvargo** [comment]
Use the run_state then: https://github.com/opscode-cookbooks/jenkins/blob/8c2eaa74ab3375c8cddb574579c0e2b6ed6fd327/libraries/_helper.rb#L207

**Comment by dgoradia-atlas** [comment]
Thanks.

So it seems I have to put it in a ruby_block which works but is it true I cannot have the run_state attribute like:
```
node.run_state['something']['else'] = ...
```
but only 1 level:
```
node.run_state['something'] = ...
```

**Comment by sethvargo** [comment]
Right - that's the way Ruby works. run_state is not a mash.

**Comment by dgoradia-atlas** [comment]
Sorry, I'm still having issues with this. Here's my recipe:
```
ruby_block 'load software data bag' do
  block do
    node.run_state['software'] = data_bag_item('software', 'insight')
  end
end

Chef::Log.error(node.run_state['software'])
```

The output:

    ERROR: nil

**Comment by sethvargo** [comment]
You are logging that message at compilation time, not runtime. By using a ruby_block, you're running at runtime, so of course that's going to be nil - the other code hasn't run yet.

**Comment by dgoradia-atlas** [comment]
Right, so I can't use run_state to store my data bag item information. Did a small test:
```
ruby_block 'software' do
  block do
    node.run_state['software'] = data_bag_item('software', 'insight')
  end
end
```
```
remote_path = "#{node.run_state['software']}/download"

file '/opt/remote' do
  content remote_path
  action :create
end
```

Ran it in a vagrant box. The contents of `/opt/remote` was `/download`.

Thanks anyway. Appreciate your help.

**Comment by sethvargo** [comment]
I think you are misunderstanding how Chef works. Move that outside of the `ruby_block`, it doesn't need to be in the ruby_block.

**Comment by dgoradia-atlas** [comment]
I probably am misunderstanding. 

I tried without the ruby_block and from the other recipe:
```
base_url = node.run_state['software']['source']['base_url']
```

Still throws error:
```
Failure/Error: end.converge(described_recipe)
     NoMethodError:
       undefined method `[]' for nil:NilClass
```
