### ISSUE TITLE
Dependency Test Coverage Differences on Windows

### ISSUE THREAD

**Issue by glasschef** [sethvargo/chefspec#594]
Chefspec 4.2.0 in Windows seems to treat coverage of dependencies differently than it does on other platforms.  For the same cookbook on Windows and OS X and Linux:

Windows:  https://gist.github.com/glasschef/dd0b7c2293a2bf413568
```
ChefSpec Coverage report generated...
 
  Total Resources:   19
  Touched Resources: 3
  Touch Coverage:    15.79%
 
Untouched Resources:
 
  chef_gem[di-ruby-lvm]              C:0
  yum_package[lvm2]                  C:0
  yum_package[s3cmd]                 C:0
  template[s3cfg]                    C:0
  yum_package[logrotate]             C:0
  directory[/etc/logrotate.d]        C:0
  template[/etc/logrotate.d/mongodb]   C:0
  yum_package[iptables]              C:0
  execute[rebuild-iptables]          C:0
  directory[/etc/iptables.d]         C:0
  template[/usr/sbin/rebuild-iptables]   C:0
  template[/etc/iptables.d/all_established]   C:0
  template[/etc/iptables.d/all_icmp]   C:0
  template[/etc/iptables.d/prefix]   C:0
  template[/etc/iptables.d/postfix]   C:0
  template[/etc/iptables.d/mongodb]   C:0
```
OS X:  https://gist.github.com/glasschef/5e7e6c7ed464b98ee481
```
ChefSpec Coverage report generated...
 
  Total Resources:   3
  Touched Resources: 3
  Touch Coverage:    100.0%
 
You are awesome and so is your test coverage! Have a fantastic day
```

**Comment by ArneCoder** [comment]
Any news on this? I have the same issue on Windows 7 and Ubuntu 14.04

**Comment by sethvargo** [comment]
I don't use Windows. So unless someone from the community is able to diagnose it, there is no news. Sorry.

**Comment by ArneCoder** [comment]
Hi, same with Ubuntu 14.04 , when i use something like this, to test for an included recipe:

 it 'includes the `jenkins` recipe' do
    expect(chef_run).to include_recipe('jenkins::master')
  end

**Comment by sethvargo** [comment]
@ArneCoder this issue is specifically about the difference in resource reporting differing on Windows vs other operating systems. Your issue is different.

**Comment by ArneCoder** [comment]
Ok thanks for your answer.
