### ISSUE TITLE
custom matchers sometimes not loaded

### ISSUE THREAD

**Issue by bleything** [sethvargo/chefspec#595]
I've noticed what seems to be a bug with how custom matchers are loaded. In a nutshell, I have a spec that only contains an expectation on a custom matcher, and it fails with a `NoMethodError` complaining that the custom matcher does not exist.

If I add an expectation on a chefspec matcher (say `include_recipe`) the spec will pass.

I've put together a [simple reproduction](https://github.com/bleything/missing-custom-matchers-repro). See the README there for more details.

**Comment by sethvargo** [comment]
It's an order thing - the Chef run hasn't been executed therefore libraries haven't yet been loaded. 

This is the reason I discourage the use of the `it { should }` format. If you  switch to the (albeit longer) `expect(chef_run).to do_something`, it should work. Can you confirm?

**Comment by bleything** [comment]
I switched to the `expect` form and it does work as expected. Thanks so much!

So, is the chef run only triggered once a chefspec matcher is called? That would explain a number of things that have been confusing me.

**Comment by sethvargo** [comment]
It's RSpec lazy-loading land. You could also use `let!(:chef_run)` and `subject!` if you feel so included.

**Comment by bleything** [comment]
Cool, thank you for the info.
