### ISSUE TITLE
Can't change default attribute values during a chef run

### ISSUE THREAD

**Issue by tden012** [sethvargo/chefspec#597]
Hi guys

Below is an example to illustrate the issue I am running into:

attributes/default.rb
-------------------------
`default['my_cookbook']['my_attribute'] = "first value"`

spec/unit/recipes/default.rb (extract)
---------------------------------------------
```
describe 'my_cookbook::default' do
    chef_run.node.default.set['my_cookbook']['my_attribute'] = "second value"
    chef_run.converge(described_recipe)
    expect(chef_run.node.default['my_cookbook']['my_attribute']).to eq "second value"
end
```

I am not setting ['my_cookbook']['my_attribute'] within my recipe, so I expected that the recipe would run with the new value. However, it seems that the convergence process re-sets the attribute "first value", even though I've set it to "second value". This causes my unit test to fail.

Am I doing something wrong here?

Further info: I've also tried the following, just to see what would happen and it also didn't work:

```
describe 'my_cookbook::default' do
    chef_run.converge(described_recipe) {
        chef_run.node.default.set['my_cookbook']['my_attribute'] = "second value"
    }
    expect(chef_run.node.default['my_cookbook']['my_attribute']).to eq "second value"
end
```

**Comment by sethvargo** [comment]
https://github.com/sethvargo/chefspec#setting-node-attributes

**Comment by tden012** [comment]
Thanks Seth. I thought I tried that example out before with no success, but I tried it again and it worked. After going through my logic, I finally figured out what went wrong (turns out that what I tried was ever so slightly different). So here's a full explanation of what I was trying to do as well as the solution for any newbies like me.


Issue 1
---------

I had defaulted an attribute in my attributes file (attributes/default.rb) file like so:
```ruby
default['my_cookbook']['my_attribute'] = "first value"
```

I was using it my recipe file (recipes/default.rb) like so:
```ruby
if node.default['my_cookbook']['my_attribute']  == "first value" then
  my_cookbook_resource1 do
    action :create
  end
else
  my_cookbook_resource2 do
    action :create
  end
end
```

Then in my unit test file (spec/unit/recipes/default_spec.rb) I had this:
```ruby
describe "my_cookbook::default" do
  context "On my context" do
    before do
      Fauxhai.mock(platform: "ubuntu", version: "12.04")
    end
    
    # SECTION 1
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new do |node, server|
        node.set['my_cookbook']['my_attribute'] = "second value"
      end
      runner.converge(described_recipe)
    end
    
    # SECTION 2
    it 'should do the second thing' do
      expect(chef_run).to create_my_cookbook_resource2
    end
  end
end
```

When I tried it out, the test in SECTION 2 failed because my_cookbook_resource1 was invoked instead of my_cookbook_resource2.

Then I thought - maybe I have to change my test so that I set attributes using 'node.default.set' instead of 'node.set'. So I changed SECTION 1 in my test to this:

```ruby
    # SECTION 1
    let(:get_runner) do
      runner = ChefSpec::ServerRunner.new(platform: platform, version: version) do |node, server|
        node.default.set['my_cookbook']['my_attribute'] = "second value"
      end
      runner.converge(described_recipe)
    end
```

This produced no results as well. So what did I do wrong?

Issue 1 Solution
--------------------

The first thing to note is that when setting attributes, you want to write to their 'default' value as much as possible. So you will usually set attributes by doing this:
```ruby
default['my_cookbook']['my_attribute'] = "some value"
```
OR
```ruby
node.default['my_cookbook']['my_attribute'] = "some value"
```

However, when reading attributes, you must always read them like this:
```ruby
my_attribute = node['my_cookbook']['my_attribute']
```

Notice that I didn't use 'default' when reading. This is done so that chef will provide the attribute value based on attribute precedence. This is really where my error was. I was trying to read the attribute by using 'node.default' and bypassing the attribute precedence mechanism. As it seems that chef_spec uses this mechanism, my tests always failed.

Using these principles, I got the following code to work:

attributes/default.rb
```ruby
default['my_cookbook']['my_attribute'] = "first value"
```
recipes/default.rb
```ruby
if node['my_cookbook']['my_attribute']  == "first value" then
  my_cookbook_resource1 do
    action :create
  end
else
  my_cookbook_resource2 do
    action :create
  end
end
```

spec/unit/recipes/default_spec.rb
```ruby
describe "my_cookbook::default" do
  context "On my context" do
    before do
      Fauxhai.mock(platform: "ubuntu", version: "12.04")
    end
    
    # SECTION 1
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new do |node, server|
        node.set['my_cookbook']['my_attribute'] = "second value"
      end
      runner.converge(described_recipe)
    end
    
    # SECTION 2
    it 'should do the second thing' do
      expect(chef_run).to create_my_cookbook_resource2
    end
  end
end
```

Issue 2 and Solution
--------------------------

The second issue for me was being able to set attributes in individual tests, rather than at the beginning of all tests. In order to do this, you have to make the following changes:
``` ruby
describe "my_cookbook::default" do
  context "On my context" do
    before do
      Fauxhai.mock(platform: "ubuntu", version: "12.04")
    end
    
    # SECTION 1.1
    let(:get_runner) do
      runner = ChefSpec::ServerRunner.new
    end
    
    # SECTION 1.2
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new do |node, server|
        node.set['my_cookbook']['my_attribute'] = "second value"
      end
      runner.converge(described_recipe)
    end

    # SECTION 2
    it 'should do the second thing' do
      runner = get_runner
      runner.node.set['my_cookbook']['my_attribute'] = "second value"
      runner.converge(described_recipe)
      expect(runner).to create_my_cookbook_resource2
    end
  end
end
```
