### ISSUE TITLE
How to double Chef::Application

### ISSUE THREAD

**Issue by walterdolce** [sethvargo/chefspec#599]
Hi @sethvargo , I consider myself a ChefSpec (and Ruby) n00b so I thought that the best place to ask questions/for suggestions would be this place. Please do point me to the right direction if there's a different place more suitable for asking for this kind of questions.

In one of my recipes I have something like this:
```
# recipes/my_recipe.rb

# some code messing with "missing_attrs" before the following..
unless missing_attrs.empty?
    Chef::Application.fatal! "You must set #{missing_attrs.join(', ')}."
```

And this is my `spec/recipes/my_recipe_spec.rb` file:
```
describe 'my_cookbook::stack' do
  let(:chef_run) do
    ChefSpec::Runner.new.converge(described_recipe)
  end
  it 'includes dependent sshd recipe' do
    %w(some_recipe other_recipe sshd).each do |recipe|
      expect(chef_run).to include_recipe("my_cookbook::#{recipe}")
    end
  end
end
```

But the recipe's code is falling onto the `fatal` case so I get:
```
my_cookbook::stack includes dependent sshd recipe
     Failure/Error: ChefSpec::Runner.new.converge(described_recipe)
     NameError:
       uninitialized constant Chef::Application
```

So my question would be, how could I double `Chef::Application` in this case?

Thanks in advance!

**Comment by sethvargo** [comment]
https://github.com/sethvargo/chefspec/issues/489#issuecomment-53592637

**Comment by walterdolce** [comment]
That was super fast! :smile: 
Thanks a lot!
