### ISSUE TITLE
Chefspec with the Environment Cookbook Pattern

### ISSUE THREAD

**Issue by ramarnat** [sethvargo/chefspec#600]
I am building a set of cookbooks that include a library cookbook and several application/wrapper cookbooks. The library cookbook does almost all the heavy listing, and is driven by several node attributes that are processed by its LWRPs. The node attributes are different for every application component and are set at the application cookbook level - these tend to be be very thin, just using chef-sugar's namespaces to set the node attributes and a wrapper recipe that calls the library recipe that does the heavy lifting. 

I see how stepping into a different cookbook's lwrp would be a bad idea. Is there a better pattern to follow to check the assertions of each app cookbook's generated by the library's LWRP without stepping in?

**Comment by sethvargo** [comment]
@ramarnat test the library cookbooks with RSpec and ChefSpec. Test the environment cookbooks with Test Kitchen.

If your attributes are just variables (i.e. they do not change the "flow" of the cookbook), then this pattern works fine. If your attributes are controlling flow (i.e. if node["foo"] this, else that), then I would recommend eliminating that pattern as quickly as possible :smile:.

I probably wouldn't use ChefSpec to test an environment cookbook, since you only care about the end state. Test the individual pieces (cookbooks) separately and then trust them as a library.

**Comment by ramarnat** [comment]
ok. specifically the lwrp's create silent response files for the application installer (Oracle apps, so you know how complex that shit can get). They all follow the same pattern, generate response xml based on node attributes set, then run the installer, then a common log handler to stream the progress. 

BUT each template generated can be pretty different. I'd like to make sure they have the right content for each application module, without running it thru an actual server build.

**Comment by sethvargo** [comment]
> Oracle apps, so you know how complex that shit can get

Sorry for the delay. I was rocking back-and-forth in a corner for a bit :smile: 

> BUT each template generated can be pretty different. I'd like to make sure they have the right content for each application module

I think you can test that with some plain-old RSpec. If you show me a code-snippet, I can write you a sample test.

**Comment by ramarnat** [comment]
> Oracle
I keep asking myself, why I bother! Then I remember those deep pockets the enterprises have. Our non oracle recipes are so much easier.

> If you show me a code-snippet, I can write you a sample test.
nah, I can write the rspec, doing it in the library right now using Rspec 3's composing matchers as described by http://aaronkromer.com/blog/2014-09-29-farewell-json-api-gems.html

The question is could I write and assert the result in the app cookbook... Wait. are you suggesting using a custom matcher that the app cookbook calls?

Here is a the spec that I am running inside the library right now:
https://gist.github.com/ramarnat/4f5a0030fcf39246a056

**Comment by sethvargo** [comment]
Yea - custom matchers are the future, especially as things become more complex in cookbooks.

**Comment by ramarnat** [comment]
Ok, then I may need some help - how could I write a custom matcher that does the step_into the lwrp?

**Comment by ramarnat** [comment]
Sorry to be a bother @sethvargo. But if you can point me in the right direction I will figure it out - how could I have the custom matcher step into the lwrp?

**Comment by sethvargo** [comment]
Hi @ramarnat 

You have the runner `step_into`, not the matcher.

**Comment by ramarnat** [comment]
right, but then I still have the issue of the app cookbook is stepping into the library cookbooks lwrp. To test all the application cookbooks affect on the converge, it seems to me I have to:
a. Add all the app node settings as different tests in the library cookbook. This is the gist that I pasted as an example Or.
b. Add the tests in the app cookbook and do a step into the library cookbooks lwrp. 
c. some other option?

**Comment by sethvargo** [comment]
Hrm. I'm not sure then. I would recommend asking on the Chef mailing list. Unfortunately I can really only focus on bugs in ChefSpec at this time, and it seems like you have a pretty specific use case. Sorry! :frowning:

**Comment by ramarnat** [comment]
I think the dilemma is primarily around to step_into or not to step_into. I think for this use case I am going to break the rule and step_into the library lwrp from the app cookbook .
