### ISSUE TITLE
`step_into` doesn't honor resource's `provides` naming

### ISSUE THREAD

**Issue by pburkholder** [sethvargo/chefspec#604]
I've illustrated this here:

https://github.com/pburkholder/chefspec/tree/pdb/provides/examples/provides

where `resources/lwrp` uses the `provides` keyword to name the resources as `foobar`:

```
actions :something
default_action :something

provides :foobar

attribute :name,   kind_of: String, name_attribute: true
```

But the `step_into` still expects the naming convention: _cookbookname_\_ _resourcename_

So this works:

```
ChefSpec::SoloRunner.new(step_into: ['provides_lwrp'])
        .converge(described_recipe)
```

but this fails 

```
ChefSpec::SoloRunner.new(step_into: ['foobar'])
        .converge(described_recipe)
```

As a naive user I expected to `step_into` the name of the resource per the `provides`, and was mystified why that wasn't happening. I think it would be a nice feature if chefspec stepped into 'foobar'.

Thanks for listening -- Peter

**Comment by sethvargo** [comment]
PRs welcome!

**Comment by pburkholder** [comment]
I'll see what I can do. I wanted to confirm it was a bug and not a feature
first.

On Tue, Jun 9, 2015 at 1:26 PM, Seth Vargo <notifications@github.com> wrote:

> PRs welcome!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sethvargo/chefspec/issues/604#issuecomment-110440009>.
>



-- 

*Peter Burkholder* — Customer Success Engineer

Unavailability: May 19, Training. June 11-12, DevOpsDays DC

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/pburkholder>  Twitter
<http://www.twitter.com/pburkholder>  Cal
<https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK>
endar

*CHEF*

CHEF.IO <http://www.chef.io/>

TM

*chef.io* <http://www.chef.io/>   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>
