### ISSUE TITLE
Can't stub_search with ServerRunner

### ISSUE THREAD

**Issue by baguasquirrel** [sethvargo/chefspec#605]
`stub_search` works just fine with `SoloRunner`, but it doesn't work with `ServerRunner`. Is there something I'm misunderstanding?

Specifically,
This doesn't work...:
```
before do
    FakeArtifactory = Struct.new('FakeArtifactory', :port)
    FakeServer = Struct.new('FakeServer', :fqdn, :artifactory)
    stub_search(:node, 'roles:ARTIFACTORY_SERVER').and_return([FakeServer.new('deploy.internal', FakeArtifactory.new(8081))])
  end

  let(:chef_run) {
    server = ChefSpec::ServerRunner.new do |node, server|
      server.create_client('my_client', { admin: true })
    end
    server.converge(described_recipe)
  }
```

...but this does:
```
before do
    FakeArtifactory = Struct.new('FakeArtifactory', :port)
    FakeServer = Struct.new('FakeServer', :fqdn, :artifactory)
    stub_search(:node, 'roles:ARTIFACTORY_SERVER').and_return([FakeServer.new('deploy.internal', FakeArtifactory.new(8081))])
  end

  let(:chef_run) {
    server = ChefSpec::SoloRunner.new
    server.converge(described_recipe)
  }
```

**Comment by sethvargo** [comment]
@baguasquirrel you cannot stub things in the server runner because it is a real chef server running in-memory. If you want to "stub" something, you need to use the `create_*` methods on the server.

**Comment by baguasquirrel** [comment]
Cool, thanks Seth.

-- sent on the fly

**Comment by ianrossi** [comment]
@baguasquirrel Would you mind sharing the code that you had success with here? I'm having a very difficult time mocking up nodes/environments, etc. with `ServerRunner` and I can't find any good, complete examples. The ChefSpec README doc shows snippets of how to create nodes, but it doesn't show how to incorporate it into a spec file with the `let` and `it` blocks.
