### ISSUE TITLE
apt_package and package seem to be duplicated on coverage tests.

### ISSUE THREAD

**Issue by cpakman** [sethvargo/chefspec#606]
I have:
```
it 'installs requisite apt packages for thrift/scribe' do
      expect(chef_run).to install_package('automake')
end
```
in tests, and 

```
package 'automake'
``` 
in my recipe.

In the coverage output, I have:

```
apt_package[automake]              cookbook/recipes/recipe.rb:11
```

if I change this to `install_apt_package`, I get

```
apt_package[automake]              cookbook/recipes/recipe.rb:11
package[automake]              cookbook/recipes/recipe.rb:11
```

**Comment by sethvargo** [comment]
Hi @cpakman 

What version of Chef are you using?

**Comment by cpakman** [comment]
I'm on chef 12.4.0, and chefspec 4.2.0

**Comment by sethvargo** [comment]
Can you try an earlier version of Chef please?

**Comment by cpakman** [comment]
sure - is there a particular version you suggest?

**Comment by sethvargo** [comment]
One that wasn't released today :smile:

**Comment by cpakman** [comment]
I had the same problem with 12.3.0, but upgraded to see if that would fix the problem. I'll try 12.0 and bisect if it works

**Comment by cpakman** [comment]
The last release it seems to work on is 12.0.3, 12.1.0 has the problem I described

**Comment by cpakman** [comment]
I found a temporary solution - to specify the platform on a chefspec runner. This doesn't seem to solve the larger problem of dealing with multiple platforms well though.

**Comment by sethvargo** [comment]
I cannot reproduce this on ChefSpec 4.3.0 and Chef 12.4.1:

```ruby
# spec/default_spec.rb
require 'chefspec'
ChefSpec::Coverage.start!

describe 'cookbook::default' do
  let(:chef_run) do
    ChefSpec::SoloRunner.converge(described_recipe)
  end

  it 'installs automake' do
    expect(chef_run).to install_package('automake')
  end
end
```

```ruby
# recipes/default.rb
package 'automake'
```

```
$ bundle exec rspec -fd

cookbook::default
  runs dpkg with test

Finished in 0.00903 seconds (files took 0.87318 seconds to load)
1 example, 0 failures


ChefSpec Coverage report generated...

  Total Resources:   1
  Touched Resources: 1
  Touch Coverage:    100.0%

You are awesome and so is your test coverage! Have a fantastic day!
```

If you are able to reproduce this issue on ChefSpec 4.3.0, please open a new issue and include the full recipe file, full spec file, and output of running Chef in debug mode. It is generally very helpful if you are able to create a cloneable, public GitHub repo that reproduces this issue with a Gemfile and no external cookbook dependencies. Thanks! :smile:
