### ISSUE TITLE
Cannot find a resource for dpkg_package on chefspec version 0.6.1

### ISSUE THREAD

**Issue by michaellihs** [sethvargo/chefspec#614]
I have a very simple recipe:

````ruby
dpkg_package 'test'
````

and a ChefSpec test for it:

````ruby
require 'spec_helper'

describe 'app_jenkins_master::dpkg' do

  let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }

  it 'runs dpkg with test' do
    expect(chef_run).to install_dpkg_package('test')
  end

end
````

When I run `bundle exec rspec -f d -c`, I get the following error message:

````
================================================================================
Recipe Compile Error in /var/folders/5g/19mv6nv972d1dh_6k7gs6k7r0000gp/T/d20150724-20763-kp86ot/cookbooks/app_jenkins_master/recipes/dpkg.rb
================================================================================

Chef::Exceptions::NoSuchResourceType
------------------------------------
Cannot find a resource for dpkg_package on chefspec version 0.6.1

Cookbook Trace:
---------------
  /var/folders/5g/19mv6nv972d1dh_6k7gs6k7r0000gp/T/d20150724-20763-kp86ot/cookbooks/app_jenkins_master/recipes/dpkg.rb:1:in `from_file'

Relevant File Content:
----------------------
/var/folders/5g/19mv6nv972d1dh_6k7gs6k7r0000gp/T/d20150724-20763-kp86ot/cookbooks/app_jenkins_master/recipes/dpkg.rb:

  1>> dpkg_package 'test'  2:  

  runs dpkg with test (FAILED - 1)

Failures:

  1) app_jenkins_master::dpkg runs dpkg with test
     Failure/Error: let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }
     Chef::Exceptions::NoSuchResourceType:
       Cannot find a resource for dpkg_package on chefspec version 0.6.1
     # /var/folders/5g/19mv6nv972d1dh_6k7gs6k7r0000gp/T/d20150724-20763-kp86ot/cookbooks/app_jenkins_master/recipes/dpkg.rb:1:in `from_file'
     # ./spec/recipe_dpkg_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/recipe_dpkg_spec.rb:9:in `block (2 levels) in <top (required)>'

Finished in 1.48 seconds (files took 2.34 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/recipe_dpkg_spec.rb:8 # app_jenkins_master::dpkg runs dpkg with test
```

The interesting thing is that my ChefSpec version is not 0.6.1 as mentioned in the error message, but the following versions are installed :

````
gem list

*** LOCAL GEMS ***

activesupport (4.2.0)
addressable (2.3.8, 2.3.6, 2.3.5)
backports (3.6.4)
berkshelf (3.3.0, 3.2.4, 3.2.3)
berkshelf-api-client (1.3.0, 1.2.1)
bigdecimal (1.2.0)
blankslate (3.1.3, 2.1.2.4)
bloomfilter-rb (2.1.1)
buff-config (1.0.1)
buff-extensions (1.0.0)
buff-ignore (1.1.1)
buff-ruby_engine (0.1.0)
buff-shell_out (0.2.0)
builder (3.2.2)
bundle (0.0.1)
bundler (1.8.0)
celluloid (0.16.0)
celluloid-io (0.16.2)
chef (12.4.1, 12.4.0, 11.16.4, 11.10.4)
chef-config (12.4.1, 12.4.0)
chef-zero (4.2.3, 2.2.1, 1.7.3)
chefspec (4.3.0, 4.2.0, 4.1.1, 3.4.0)
chunky_png (1.3.4, 1.3.3)
classifier-reborn (2.0.3)
cleanroom (1.0.0)
coderay (1.1.0)
coffee-script (2.3.0)
coffee-script-source (1.9.1)
colorator (0.1)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
cookiejar (0.3.2)
crack (0.4.2)
daemons (1.2.2, 1.1.9)
dbgit (0.0.1)
dep-selector-libgecode (1.0.2, 1.0.0)
dep_selector (1.0.3, 1.0.0)
diff-lcs (1.2.5)
em-http-request (1.1.2)
em-socksify (0.3.0)
em-synchrony (1.0.3)
em-websocket (0.3.8)
erubis (2.7.0)
eventmachine (1.0.7, 1.0.3)
execjs (2.4.0)
faraday (0.9.1)
fast-stemmer (1.0.2)
fauxhai (2.3.0, 2.2.0, 2.1.0)
ffi (1.9.10, 1.9.8, 1.9.7, 1.9.6)
ffi-yajl (2.2.2, 2.2.1, 2.2.0, 1.3.1)
foodcritic (4.0.0, 3.0.3)
gemoji (2.1.0)
gherkin (2.12.2, 2.11.8)
github-pages (33)
github-pages-health-check (0.2.2)
gitlab (3.4.1, 3.4.0)
gli (2.13.0, 2.9.0)
hashie (2.1.2)
highline (1.7.2, 1.6.21)
hitimes (1.2.2)
html-pipeline (1.9.0)
htmlentities (4.3.3, 4.3.2, 4.3.1)
http_parser.rb (0.6.0)
httparty (0.13.5)
httpclient (2.6.0.1)
i18n (0.7.0)
io-console (0.4.2)
ipaddress (0.8.0)
jekyll (2.5.3, 2.4.0)
jekyll-coffeescript (1.0.1)
jekyll-gist (1.1.0)
jekyll-mentions (0.2.1)
jekyll-paginate (1.1.0)
jekyll-redirect-from (0.6.2)
jekyll-sass-converter (1.3.0, 1.2.0)
jekyll-sitemap (0.6.3)
jekyll-watch (1.2.1)
jemoji (0.4.0)
json (1.8.3, 1.8.2, 1.8.1, 1.7.7)
kitchen-vagrant (0.15.0)
knife-cookbook-doc (0.15.0, 0.10.0)
knife-cookbook-readme (0.2.1)
kramdown (1.6.0, 1.5.0)
librarian (0.1.2)
librarian-chef (0.0.4)
libyajl2 (1.2.0)
liquid (2.6.2, 2.6.1)
listen (2.9.0)
lolcat (42.1.0)
maruku (0.7.0)
mercenary (0.3.5)
method_source (0.8.2)
mime-types (2.6.1, 1.25.1)
mini_portile (0.6.2, 0.6.1, 0.6.0, 0.5.2)
minitar (0.5.4)
minitest (5.5.1, 4.3.2)
mixlib-authentication (1.3.0)
mixlib-cli (1.5.0, 1.4.0)
mixlib-config (2.2.1, 2.1.0)
mixlib-log (1.6.0)
mixlib-shellout (2.1.0, 2.0.0, 1.6.1, 1.4.0)
moneta (0.6.0)
multi_json (1.11.2, 1.11.1, 1.11.0, 1.10.1, 1.9.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
net-dns (0.8.0)
net-http-persistent (2.9.4)
net-scp (1.2.1)
net-ssh (2.9.2, 2.9.1, 2.8.0)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.1, 1.2.0)
net-telnet (0.1.1)
nio4r (1.1.1, 1.1.0)
nokogiri (1.6.6.2, 1.6.5, 1.6.3.1, 1.6.1, 1.5.11)
octokit (3.8.0, 3.7.0)
ohai (8.5.0, 7.4.0, 6.22.0)
paint (0.8.7)
parallel (1.6.0, 1.0.0)
parslet (1.7.0, 1.5.0)
pdfkit (0.5.4)
plist (3.1.0)
polyglot (0.3.5, 0.3.4)
posix-spawn (0.3.10)
pry (0.10.1, 0.9.12.6)
psych (2.0.0)
public_suffix (1.4.6)
puma (1.6.3)
pygments.rb (0.6.2, 0.6.1)
rack (1.6.4, 1.6.1, 1.5.2)
rack-protection (1.5.3, 1.5.2)
rack-test (0.6.3)
rake (10.4.2, 10.3.2, 10.2.2, 0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdiscount (2.1.7)
rdoc (4.0.0)
redcarpet (3.2.3, 3.2.2, 3.1.2, 3.1.0)
RedCloth (4.2.9)
redis (3.1.0)
rest-client (1.6.7)
retryable (2.0.1)
ridley (4.2.0, 4.1.2)
rspec (3.3.0, 3.2.0, 3.1.0, 2.99.0, 2.14.1)
rspec-core (3.3.2, 3.3.1, 3.2.3, 3.2.1, 3.1.7, 2.99.0, 2.14.8)
rspec-expectations (3.3.1, 3.3.0, 3.2.1, 3.2.0, 3.1.2, 2.99.0, 2.14.5)
rspec-its (1.2.0, 1.1.0)
rspec-mocks (3.3.2, 3.3.1, 3.2.1, 3.1.3, 2.99.0, 2.14.6)
rspec-support (3.3.0, 3.2.2, 3.1.2)
rspec_junit_formatter (0.2.3)
ruby-progressbar (1.5.1)
ruby_unicornsay (0.0.1)
rufus-lru (1.0.5)
safe_yaml (1.0.4)
sass (3.4.13, 3.4.11)
sawyer (0.6.0)
semverse (1.2.1)
serverspec (2.19.0, 2.14.1, 2.9.1, 2.6.0)
sfl (2.2)
showoff (0.9.10.8, 0.9.7)
sinatra (1.4.6, 1.4.4)
sinatra-base (1.4.0)
sinatra-contrib (1.4.2)
sinatra-cross_origin (0.3.2)
sinatra-websocket (0.3.1, 0.3.0)
slop (3.6.0, 3.5.0)
solve (1.2.1)
specinfra (2.37.8, 2.37.5, 2.37.1, 2.36.15, 2.36.14, 2.36.12, 2.28.1, 2.17.1, 2.10.0)
syslog-logger (1.6.8)
systemu (2.6.5, 2.6.4, 2.5.2)
terminal-table (1.5.2, 1.4.5)
test-kitchen (1.2.1)
test-unit (2.0.0.0)
thin (1.6.3, 1.6.1)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.1, 1.4.1)
timers (4.0.1)
toml (0.1.2)
treetop (1.6.3, 1.5.3, 1.4.15)
trollop (1.16.2)
tzinfo (1.2.2)
uuidtools (2.1.5)
vagrant (1.5.0)
varia_model (0.4.0)
webmock (1.21.0)
webrick (1.3.1)
wmi-lite (1.0.0)
yajl-ruby (1.2.1, 1.1.0)
```

Question is: what am I doing wrong? Thx for any help on this issue!

**Comment by joerg** [comment]
The chefspec version really is strange. Is there a version constraint in your Gemfile?

**Comment by sethvargo** [comment]
Hi @michaellihs 

Thank you for open opening an issue. ChefSpec is working as intended here, but this is a misconception (and design flaw) of Chef in my opinion.

Chef conditionally loads resources based off the platform it is running. For example, `windows_resource` is not available as a resource when running on FreeBSD. Similarly, `dpkg_package` is not a resource that is loaded by default.

You need to tell Chef that you want to impersonate a debian/ubuntu-based system:

```ruby
ChefSpec::SoloRunner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe)
```

**Comment by michaellihs** [comment]
Hey @sethvargo and @joerg - thx to both of you for your replies.

Joerg: no, there is no constraint in the Gemfile.

I will try Seth's solution tomorrow. Interesting though: everything is already working perfectly fine, when I am running `chef exec rspec` on my Mac. Seth's hint explains, why it worked on the Ubuntu based Jenkins server in CI.

Thanks again!

**Comment by michaellihs** [comment]
Hey @sethvargo - just wanted to let you know that after fixing the specs following your advice with 

````ruby
  let(:chef_run) { ChefSpec::SoloRunner.new(platform: 'ubuntu', version: '14.04').converge(described_recipe) }
````

everything works like a charm - thanks a lot!
