### ISSUE TITLE
chefspec test attempts connection to https://localhost/nodes/fauxhai.local

### ISSUE THREAD

**Issue by mick-m** [sethvargo/chefspec#619]
I'm writing a simple chefspec unit test on a resource action. My recipes is as follows:

```ruby
require 'chefspec'

#This is the ceph_lwrp::pools_spec recipe.

describe 'ceph_lwrp::pools' do
  let(:runner) { ChefSpec::Runner.new }
  let(:chef_run) { runner.converge(described_recipe) }
  let(:node) { runner.node }

  it "creates ceph user pools" do
    node.set['ceph']['user_pools'] = [{name: "test",pg_num: 128}]
    expect(chef_run).to execute(ceph_pool["test"])
  end
end
```

I'm expecting this to return as successful, but instead it attempts (and fails) to connect to a non-existent fauxhai chefserver. 

The output is as follows:

```
.......[2015-07-29T16:05:58+01:00] WARN: We are genereting a new uuid for fsid
[2015-07-29T16:05:58+01:00] ERROR: Connection refused connecting to https://localhost/nodes/fauxhai.local, retry 1/5
[2015-07-29T16:06:03+01:00] ERROR: Connection refused connecting to https://localhost/nodes/fauxhai.local, retry 2/5
[2015-07-29T16:06:08+01:00] ERROR: Connection refused connecting to https://localhost/nodes/fauxhai.local, retry 3/5
[2015-07-29T16:06:13+01:00] ERROR: Connection refused connecting to https://localhost/nodes/fauxhai.local, retry 4/5
[2015-07-29T16:06:18+01:00] ERROR: Connection refused connecting to https://localhost/nodes/fauxhai.local, retry 5/5

================================================================================
Recipe Compile Error in /Users/mickm/workspace/cookbooks/ceph_lwrp/vendor/cookbooks/ceph_lwrp/recipes/pools.rb
================================================================================

Errno::ECONNREFUSED
-------------------
Connection refused - Connection refused connecting to https://localhost/nodes/fauxhai.local, giving up
```

I couldn't find anything about this online and I have other chefspec tests in my cookbook which work as expected. Any help is greatly appreciated. Thanks.

**Comment by sethvargo** [comment]
Can you show your recipe?

**Comment by sethvargo** [comment]
Specifically `cookbooks/ceph_lwrp/recipes/pools.rb` please? Your recipe is trying to make some external HTTP call.

**Comment by mick-m** [comment]
Sure, thanks. The recipe logic is as follows:

```ruby
if node['ceph']['user_pools']
  # Create user-defined pools
  node['ceph']['user_pools'].each do |pool|
    ceph_pool pool['name'] do
      pg_num pool['pg_num']
      create_options pool['create_options'] if pool['create_options']
    end
  end
end
```

**Comment by sethvargo** [comment]
And what does the ceph_pool LWRP define?

**Comment by mick-m** [comment]
The above is the ceph_lwrp::pool recipe:
- this block was at the end of original upstream ceph::mon recipe, but it was attempting to create ceph user pools before the required ceph services were up, so I unwound it (successfully) in a separate recipe.
- I then created the above ceph_lwrp::pool recipe and placed it further down the run_list, so it now executes when all ceph services are up and running.

Hope this makes sense : )

**Comment by sethvargo** [comment]
There is an LWRP named `ceph_pool` somewhere. Without seeing what that LWRP does, I can't help you...

**Comment by mick-m** [comment]
'ceph_pool' is just a resource being run in the recipe.

**Comment by mick-m** [comment]
Actually, wait. Let me check that and get back to you. Thanks.

**Comment by mick-m** [comment]
Yeah, you're absolutely correct. The 'ceph_pool' LWRP exists in the upstream cookbook:

- the resource: https://github.com/ceph/ceph-cookbook/blob/master/resources/pool.rb
- the provider: https://github.com/ceph/ceph-cookbook/blob/master/providers/pool.rb

**Comment by mick-m** [comment]
There doesn't appear to be anything in the LWRP making an external HTTP request.

**Comment by sethvargo** [comment]
Chef Search is an HTTP request: https://github.com/ceph/ceph-cookbook/blob/master/libraries/default.rb#L1

**Comment by mick-m** [comment]
OK, thanks very much for your assistance.
