### ISSUE TITLE
How to pass new_resource variable in a chefspec test?

### ISSUE THREAD

**Issue by equick** [sethvargo/chefspec#626]
Hi,

I raised this on stackoverflow at http://stackoverflow.com/questions/32083103/how-to-pass-new-resource-variable-in-a-chefspec-test as well so sorry for duplicating but not sure it goes to the same audience.

I'm writing a chefspec test for an LWRP which does ```settings = new_resource.settings``` and stuck on how I can get that value passed into the chefspec test?

Thanks for any help.

Edward

**Comment by sethvargo** [comment]
Hi @equick 

This issue tracker is reserved for bug reports and feature requests. Please ask general usage questions on the Chef mailing list or Stackoverflow (as you've done). Thanks! :smile:

**Comment by equick** [comment]
Understood. Thanks will do. Sorry about that.
