### ISSUE TITLE
Testing setting registry key fails due to value comparison

### ISSUE THREAD

**Issue by pvandervelde** [sethvargo/chefspec#629]
I'm trying to test setting a registry key value in ChefSpec but I'm getting a weird failure.

My chef code to set the registry values is: 

    registry_key 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Dnscache\\Parameters' do
      values [
        {
          name: 'NegativeCacheTime',
          type: :dword,
          data: 0x0
        },
        {
          name: 'NetFailureCacheTime',
          type: :dword,
          data: 0x0
        },
        {
          name: 'NegativeSOACacheTime',
          type: :dword,
          data: 0x0
        }]
      action :create
    end

And to test that I have the following spec code:

    it 'disables the DNS caching of negative responses' do
        expect(chef_run).to create_registry_key('HKLM\\SYSTEM\\CurrentControlSet\\Services\\Dnscache\\Parameters').with(
          values: [
            {
              name: 'NegativeCacheTime',
              type: :dword,
              data: 0x0
            },
            {
              name: 'NetFailureCacheTime',
              type: :dword,
              data: 0x0
            },
            {
              name: 'NegativeSOACacheTime',
              type: :dword,
              data: 0x0
            }])
      end

When running the test I get the following error:

    ops_resource_core::consul_as_dns disables the DNS caching of negative responses
           Failure/Error: expect(chef_run).to create_registry_key('HKLM\\SYSTEM\\CurrentControlSet\\Services\\Dnscache\\Parameters').with(
             expected "registry_key[HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters]" to have parameters:

               values [{:name=>"NegativeCacheTime", :type=>:dword, :data=>0}, {:name=>"NetFailureCacheTime", :type=>:dword, :data=>0}, {:name=>
      "NegativeSOACacheTime", :type=>:dword, :data=>0}], was [{:name=>"NegativeCacheTime", :type=>:dword, :data=>"cfcd208495d565ef66e7dff9f9876
      4da"}, {:name=>"NetFailureCacheTime", :type=>:dword, :data=>"cfcd208495d565ef66e7dff9f98764da"}, {:name=>"NegativeSOACacheTime", :type=>:
      dword, :data=>"cfcd208495d565ef66e7dff9f98764da"}]

It is clear why the values are not the same but what I don't understand is where does the `cfcd208495d565ef66e7dff9f98764da` value come from. I'm assuming it's some kind of hash / encrypted value of 0, but if that is the case how am I supposed to test that the correct values are being set?

**Comment by sethvargo** [comment]
That's the MD5 sum of "0". Chef must be converging this somehwere, since ChefSpec doesn't change any inputs.

**Comment by pvandervelde** [comment]
Ok thanks. I guess I'll just put the MD5 sum in my spec then.

**Comment by chrisgit** [comment]
@pvandervelde I got the same error today, a quick look at the Chef resource for Registry Key showed up this

````
      def values(arg = nil)
        if not arg.nil?
			# Code for assignment ...
        elsif self.instance_variable_defined?(:@values)
          scrub_values(@values)
        end
      end

      def scrub_values(values)
		# For each value ...
          if needs_checksum?(scrubbed_value)
			# Apply checksum ...
		  end
        end
        # Returned scrubbed values
      end

      # Some data types may raise errors when sent as json. Returns true if this
      # value's data may need to be converted to a checksum.
      def needs_checksum?(value)
        unsafe_types = [:binary, :dword, :dword_big_endian, :qword]
        unsafe_types.include?(value[:type])
      end
````

No idea why the value needs to be converted to a checksum, @sethvargo ?

Using pry I could see that the resource has an unscrubbed_values method so for the purpose of testing I changed the expectation, therefore 

````
it 'disables the DNS caching of negative responses' do
    expect(chef_run).to create_registry_key('HKLM\\SYSTEM\\CurrentControlSet\\Services\\Dnscache\\Parameters').with(
      unscrubbed_values: [
        {
          name: 'NegativeCacheTime',
          type: :dword,
          data: 0x0
        },
        {
          name: 'NetFailureCacheTime',
          type: :dword,
          data: 0x0
        },
        {
          name: 'NegativeSOACacheTime',
          type: :dword,
          data: 0x0
        }])
  end
````
