### ISSUE TITLE
Properly stubing search results

### ISSUE THREAD

**Issue by retr0h** [sethvargo/chefspec#63]
I am attempting to test the following cookbook, which makes a search call.

https://github.com/retr0h/cookbook-conserver/blob/master/recipes/server.rb

I have tried the techniques from [issue 18](https://github.com/acrmp/chefspec/issues/18) with no luck.
I have also tried the technique listed on the chefspec gh page.

```
emopop:cookbook-conserver(master)% rspec cookbooks/conserver 
..[2012-10-08T18:04:31-07:00] ERROR: Connection refused connecting to localhost:4000 for /search/node, retry 1/5
```

Any ides what I am doing wrong?  I can stub out the call to include_recipe ok.

**Comment by rneu31** [comment]
The suggestion by @jimhopp is using now deprecated syntax. 

```
Deprecation Warnings:

Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead.
```

Figured I'd comment my solution here for anyone who finds this thread looking for help.

```
before do
  allow_any_instance_of(Chef::Recipe)
    .to receive(:search).with(:node, "some_stubbed_search")
    .and_return(['whatever_you_need'])
end
```
