### ISSUE TITLE
Attributes not being set to nil

### ISSUE THREAD

**Issue by ersmith** [sethvargo/chefspec#630]
When overriding an attribute and setting it to ``nil`` the override is not being honored:

```
it 'should not download the file if the source is nil' do
  chef_run.node.set['test']['source'] = nil
  chef_run.converge('test::default')

  expect(chef_run).to_not create_remote_file('/tmp/download')
end
```

If ``nil`` is replaced with other values (such as ``'test'``) the attribute is successfully overridden.

**Comment by sethvargo** [comment]
This is because of attribute merging. The nil value is always going to be overwritten by the default. I think you need to use .override:

**Comment by ersmith** [comment]
Thanks Seth.  It actually appears to be a quirk in chef (https://github.com/chef/chef/issues/1507) where it is impossible to override an attribute with nil.  The work around seems to involve using ``node.rm`` to delete it and then overriding the attribute.

**Comment by pc-mreeves** [comment]
@ersmith - it looks like the normal chefspec node setting mechanism doesn't work though?

e.g. 
```
chef_run.node.rm('foo', 'bar', 'zap')
chef_run.node.normal[:foo][:bar][:baz] = 'bad_example'
```

**Comment by iancward** [comment]
@pc-mreeves I'm seeing the same thing; I have an attribute namespace at, e.g. `node['my_cookbook']['data']`, with a few different hashes underneath it and I'd like to delete everything at that level and add only a single hash underneath. It doesn't appear to work at all.
