### ISSUE TITLE
run_bash fails

### ISSUE THREAD

**Issue by geleman** [sethvargo/chefspec#632]
I have a bash script:

```ruby
if node['mysql_config']['instance_name'] == 'slave'
  bash 'start replication' do
    user 'mysql'
    code <<-EOF
    mysql -uroot -p#{slvopts['password']} -S /tmp/mysqld.sock -e "change master to master_host = '10.84.101.100',
    master_log_file = 'mysql-bin.000001',
    master_log_pos = 120,
    master_user = 'repl',
    master_password = '#{replopts['password']}',
    master_port = 3306;
    start slave;"
    EOF
    not_if "mysql -uroot -p#{slvopts['password']} -S /tmp/mysqld.sock -e
    'select * from information_schema.global_status where variable_name like \"slave_running\";' | grep ON"
    action :run
  end
end
```

When I test it: 

```ruby
describe 'mysql_config::start_replication' do
  let(:replication) { ChefSpec::SoloRunner.converge('mysql_config::start_replication') }
    it 'runs bash[start replication]' do
    expect(replication).to run_bash('start replication')
  end
end
```

This is the error:

```
  1) mysql_config::start_replication runs bash[start replication]
     Failure/Error: expect(replication).to run_bash('start replication')
       expected "bash[start replication]" with action :run to be in Chef run. Other bash resources:
``` 

I'm not sure what the issue is here

**Comment by sethvargo** [comment]
Are you setting mysql_config.instance_name = slave somewhere? I don't see that in your code.

**Comment by geleman** [comment]
Actually it does via a role cookbook but wasn't thinking to set it via a node.set. I will give it a go and report back.

**Comment by geleman** [comment]
describe 'mysql_config::start_replication' do
  let(:replication) do
    ChefSpec::SoloRunner.new(
      platform: 'centos',
      version: '6.6',
    ) do |node|
      node.set['mysql_config']['instance_name'] = 'slave'
    end.converge('mysql_config::start_replication')
  end

  it 'runs bash[start replication]' do
    expect(replication).to run_bash('start replication')
  end
end

still error:

Failures:

  1) mysql_config::start_replication runs bash[start replication]
     Failure/Error: expect(replication).to run_bash('start replication')
       expected "bash[start replication]" with action :run to be in Chef run. Other bash resources:

**Comment by sethvargo** [comment]
Hi @michaelklishin 

Can you please put together a github repo with a reproduction case and I can look into it? What version of ChefSpec are you using?

**Comment by geleman** [comment]
Is this intended for me? If so do you just need the cookbook recipe and spec test? The repo it is in is public so you can do a fork. Also I'm just worried it's a syntax error between the recipe and test but not fully sure I have it calling correctly.

**Comment by geleman** [comment]
If you do fork it let me know and I'll make sure it is committed with what I have posted here.

**Comment by sethvargo** [comment]
Hi @geleman 

Yea - I'm not sure why GitHub selected Michael as the first ping. Where does the repo live?

**Comment by geleman** [comment]
https://github.com/geleman/mysql_config

It's the start_replication recipe and start_replication_spec test.
There is a before do in the original file. I left that out in the original
post to save space. It is same error with or without that in there.

Thanks for all the help

**Comment by sethvargo** [comment]
Hi @geleman 

The issue is that you're using `node.normal` instead of `node.default` for your attributes.rb file. normal > set, so the attribute wasn't being overridden.

**Comment by geleman** [comment]
There is a role cookbook that overrides that setting. The cookbook and replications starts with not issues so I'm not seeing how this will make a difference?

**Comment by geleman** [comment]
The role cookbook is called slave and it has attributes that change that setting.

**Comment by geleman** [comment]
I changed the node.set to node.override in the spec test and i'm now getting new error about stubbing the command and I stub the command and it still fails

**Comment by sethvargo** [comment]
@geleman I suggest reading the attribute precedence reference material for more information. This is not a ChefSpec issue, but just the way you are expecting attributes to merge: https://docs.chef.io/attributes.html

The error about stubbing the command is expected. Please see this information in the README: https://github.com/sethvargo/chefspec#stubbing

**Comment by geleman** [comment]
I know about attributes and fixed that in the spec test itself which was creating the stub command issues. I initially stubbed it incorrectly and fixed it now. I was reading the stub example and not the readme and set it up wrong. It is now fixed.  I appreciate the help and didn't even think of attribute value at all.
