### ISSUE TITLE
question/advice on berkshelf dependency and bundler

### ISSUE THREAD

**Issue by dpetzel** [sethvargo/chefspec#644]
This is more of a question/request for guidance than an actual issue. A few folks in our organization have been bumping up against https://github.com/berkshelf/berkshelf/issues/1466, which I don't believe is a chefspec issue, however reset makes the following statement:

> If you have a tool that needs to leverage Berkshelf, regardless of which language it is written in, it should shell out to the berks command

It doesn't seem that chefspec does this, but instead loads berks as a gem. We have a number of cookbooks that all have a variety of versions of Chefspec. We've historically used Gemfiles to control this. This is especially important for some of older cookbooks which have not been upgraded to work with Rspec3 yet. As a result of us running rspec via bundler we run into the error above.

So the general question is if we should be avoiding the use of Chefspec via Bundler. and if so is there a better way to handle multiple cookbooks with different version requirements?

Thanks

**Comment by sethvargo** [comment]
The recommendation is to use ChefSpec with ChefDK.
