### ISSUE TITLE
ChefSpec::ServerRunner is difficult to use

### ISSUE THREAD

**Issue by ianrossi** [sethvargo/chefspec#647]
I have working code with `ChefSpec::Server` but I have tried many iterations of `ChefSpec::ServerRunner` and I just can figure out in which `let` or `it` block to invoke it in combination with creating nodes and setting node attributes. Can someone help me understand how to properly use `ChefSpec::ServerRunner` to create nodes to mock Chef search? I just couldn't find a good complete example, but I took a hint from @spheromak's code [here](https://github.com/chef-brigade/etcd-cookbook/blob/master/test/spec/cluster_spec.rb), which is how I ended up at `ChefSpec::Server`. I'm running chefspec 4.3.0. Perhaps someone could show how to modify this code for `ChefSpec::ServerRunner`? Thanks.
```ruby
require 'spec_helper'

describe 'fit-monitor::jenkins' do

  let(:chef_run) { ChefSpec::Runner.new }

  let(:master_node) do
    stub_node('master_node', run_list: 'monitor::master') do |node|
      node.set[:ipaddress] = '1.2.3.4'
    end
  end

  it 'includes the fit-monitor::client recipe' do
    chef_run do |node, server|
      ChefSpec::Server.create_node(master_node)
      node.set[:monitor][:environment_aware_search] = false
      server.update_node(node)
    end.converge(described_recipe)
    expect(chef_run).to include_recipe('fit-monitor::client')
  end

end
```

**Comment by miroswan** [comment]
I haven't stubbed out search, but you might be able to use:
```
allow_any_instance_of(Chef::Recipe).to receive(:search).with(your_params*).and_return(expected_output)
```
in the block passed to ChefSpec::ServerRunner. I've stubbed out other methods this way, but I don't use search much. You might have some luck asking in the chefspec or chef channels in freenode as well.

**Comment by miroswan** [comment]
This worked for me. In the default recipe I just have one search method that is called. You would probably want to have the and_return method actually include your stubbed results. 

```
require 'spec_helper'

describe 'mycookbook::default' do

  let(:chef_run) do
    ChefSpec::SoloRunner.new do
      allow_any_instance_of(Chef::Recipe).to receive(:search).and_return(Hash.new)
    end.converge(described_recipe)
  end

  it "mycookbook::default calls search and returns an empty hash" do
    expect_any_instance_of(Chef::Recipe).to receive(:search).and_return({})
    chef_run
  end

end
```

results

```
mycookbook::default
  mycookbook::default receives search and returns an empty hash

Finished in 0.7406 seconds (files took 1.71 seconds to load)
1 example, 0 failures
```

**Comment by miroswan** [comment]
This appears to work with ServerRunner as well.

**Comment by miroswan** [comment]
Also, this: https://github.com/sethvargo/chefspec#search

**Comment by miroswan** [comment]
Alternatively, if you needed to test to make sure that search was working as expected, I suppose you could do something like this. It's kind of clunky though. 

```
require 'spec_helper'

describe 'mycookbook::default' do

  let(:chef_run) do
    ChefSpec::ServerRunner.new do |node, server|
      node1 = stub_node do |node|
        node.set['foo'] = 'bar'
      end
      server.create_node(node1)
    end.converge(described_recipe)
  end

  it "mycookbook::default receives search and sets attribute foo to bar" do
    expect(chef_run.node['results'][0].attributes['foo']).to eq('bar')
  end

end
```

The default recipe looks like this:

```
node.default['results'] = search(:node, 'foo:bar')
```

**Comment by kzw** [comment]
ServerRunner does not behave as drop-in replacement for solorunner when you need to coverge a role and if you need an environment.  SoloRunner can load environments and roles data from files on disk automagically.  It appears that you need to specifically create (i.e. upload to the chef-zero) if you use any of the role and environments.

**Comment by sethvargo** [comment]
It looks like there are some good solutions here, so I'm going to close this issue. If you'd like to update any part of the README or instructions, I'll gladly review a PR :smile:
