### ISSUE TITLE
Stub resource in dependent cookbook to verify notify in current recipe 

### ISSUE THREAD

**Issue by genslein** [sethvargo/chefspec#658]
Hey all,

After much digging through a few links and issues, I think I am stuck. I have an nginx wrapper cookbook that I am trying to enable the default site and send the notify nginx restart. When I go to test, I can't find the appropriate service and as a result, subsequently fail.

```ruby
#nginx_wrapper::default
include_recipe 'nginx::source'

link '/opt/nginx/sites-enabled/default' do
  to '/opt/nginx/sites-available/default'
  notifies :restart, 'service[nginx]'
end
```

my chefspec file is as follows:
```ruby
require 'chefspec'
require 'chefspec/berkshelf'

describe 'nginx_wrapper::default' do
  let(:chef_run) do
    ChefSpec::SoloRunner.new(platform: 'ubuntu',
                             version: '14.04').converge(described_recipe)
  end

  it 'includes nginx wrapper cookbook' do
    expect(chef_run).to include_recipe('nginx::source')
  end

  it 'has the default nginx config' do
    expect(chef_run).to create_link('/opt/nginx/sites-enabled/default')
    expect(chef_run).to notify('service[nginx]').to(:restart)
  end
end

```

The error I get as follows:
```
1) nginx_wrapper::default enables the default nginx config
     Failure/Error: expect(chef_run).to notify('service[nginx]').to(:restart)

     NoMethodError:
       undefined method `immediate_notifications' for #<ChefSpec::SoloRunner:0x007ff2f39dca40>
     # /Users/genslein/.rvm/gems/ruby-2.1.5/gems/chefspec-4.4.0/lib/chefspec/solo_runner.rb:267:in `method_missing'
     # /Users/genslein/.rvm/gems/ruby-2.1.5/gems/chefspec-4.4.0/lib/chefspec/matchers/notifications_matcher.rb:95:in `immediate_notifications'
     # /Users/genslein/.rvm/gems/ruby-2.1.5/gems/chefspec-4.4.0/lib/chefspec/matchers/notifications_matcher.rb:91:in `all_notifications'
     # /Users/genslein/.rvm/gems/ruby-2.1.5/gems/chefspec-4.4.0/lib/chefspec/matchers/notifications_matcher.rb:26:in `matches?'
     # ./test/spec/default_spec.rb:72:in `block (2 levels) in <top (required)>'
```

I thought maybe an example like below might work:
```ruby
  before do
    allow_any_instance_of(Chef::Recipe)
        .to receive(:include_recipe)
  end

  it 'includes nginx wrapper cookbook' do
    expect_any_instance_of(Chef::Recipe)
        .to receive(:include_recipe).with('nginx::source')
    chef_run
  end
```
But unfortunately, I get a similarly frustrating error
```
Chef::Exceptions::ResourceNotFound:
       resource link[/opt/nginx/sites-enabled/default] is configured to notify resource service[nginx] with action restart, but service[nginx] cannot be found in the resource collection. 
       link[/opt/nginx/sites-enabled/default] is defined in /var/folders/s7/1gpdclhd3cn_99l0_8c8pyg14w5ysn/T/d20151204-85705-q9c6th/cookbooks/nginx_wrapper/recipes/default.rb:17:in `from_file'
```
I have used #176, #397, and #253 to try and fake my 'service[nginx]' during a chefspec run. I've also used references to the current nginx cookbook [example spec](https://github.com/miketheman/nginx/blob/cdc31cd03606c5ae1914c7fbc93b2a7635647cd2/spec/shared_examples/service.rb) and another possible workaround here from easybib [spec shown](https://github.com/fh/easybib-cookbooks/blob/0a9f7935371d6dc89796e83041cf5092bd96167a/easybib/spec/easybib_deploy_spec.rb). Any suggestions are greatly appreciated as I feel I am just doing something plainly wrong.

**Comment by mtricolici** [comment]
You can add missing resource during runtime in this way:

`describe 'mycookbook::default' do
  context 'something' do
    let(:solo) do
      ChefSpec::SoloRunner.new
    end 

    let(:chef_run) do
      solo.converge(described_recipe) do
        solo.resource_collection.insert(Chef::Resource::Service.new('apache2', solo.run_context))
      end 
    end 

    it 'runs without errors' do
      allow_any_instance_of(Chef::Recipe).to receive(:include_recipe)
      chef_run
    end 
  end 
end`

**Comment by genslein** [comment]
:metal: @mtricolici
