### ISSUE TITLE
with_content broken when using do/end syntax

### ISSUE THREAD

**Issue by miroswan** [sethvargo/chefspec#664]
When passing a block to the with_content method with do/end syntax, I get an ArgumentError: Must specify expected content or a block!

It is best that do/end syntax is used when working with multiple lines. This should be supported.

**Comment by miroswan** [comment]
using block_given? might give us better results.

**Comment by aibou** [comment]
you can avoid this error when you use `{}` instead of `do / end`. like this:

```ruby
expect(chef_run).to render_file('/etc/hosts').with_content{|content|
  expect(content).to match(/127\.0\.0\.1 localhost/)
}
```

or

```ruby
```

**Comment by sethvargo** [comment]
#666 fixes this, no?
