### ISSUE TITLE
ChefSpec for FileEdit in ruby_block

### ISSUE THREAD

**Issue by joerg** [sethvargo/chefspec#670]
It would be super handy to have something like `expect(chef_run).to render_file(...).with_content(...)` for FileEdits. Generally I don't like FileEdits as they are super hard to write and maintain but sometimes you don't have any other chance and in these situations I would love to test my regexes against some sample content and see if the file is rendered correctly.
I already tried using FakeFS for this, but after trying some time and not even getting anywhere near to actually converging the recipe I gave up. Basically I tried something like this

```
FakeFS do
  FileUtils.mkdir_p '/tmp/test'
  FileUtils.touch '/tmp/test/file'
  chef_run
  expect(File.read('/tmp/test/file')).to_include 'my text'
end
```

Has anyone every tried and succeeded with this or something similar? Or even better: Is there any chance ChefSpec will receive support for this.

**Comment by sethvargo** [comment]
Hi @joerg 

Your best bet here is to use mocks/stubs. Remember that ChefSpec is a unit testing framework, so you really want to assert that the proper _messages_ were sent. Typically, this looks something like this:

```
expect(Chef::FileEdit).to receive(:write).with(whatever)
```

Thanks! :smile:
