### ISSUE TITLE
documentation for `with_` keyword

### ISSUE THREAD

**Issue by icberg7** [sethvargo/chefspec#672]
I looked at https://github.com/sethvargo/chefspec#render_file and wanted to know if I could use `with_<attribute>` keyword to perform regex matching against other resource properties, and it appears to work.
I'm not sure if this is _supported_, but if it is, it would be nice to have a snippet in the documentation saying as such.

For example, instead of having to hard code an assertion:
```
it 'points dockerrepo to repo proxy' do
  expect(chef_run).to create_yum_repository('dockerrepo').with(
    baseurl: 'my_full_url_here'
  )
  end
end
```

I was able to get this to work:
```
it 'points dockerrepo to repo proxy' do
  expect(chef_run).to create_yum_repository('dockerrepo')
    .with_baseurl(/my_internal_proxy_hostname/)
  end
end
```

**Comment by sethvargo** [comment]
Hi @icberg7 

All matches support regular expressions, and this is documented in the API documentation: http://www.rubydoc.info/github/sethvargo/chefspec
