### ISSUE TITLE
chocolatey_package matchers are missing

### ISSUE THREAD

**Issue by dougireton** [sethvargo/chefspec#673]
I'm working on a PR for this.

Chef-Client 12.7 introduces a [`chocolatey_package` resource](https://docs.chef.io/release/12-7/release_notes.html).

ChefSpec should include a set of `chocolatey_package` resource matchers.

**Comment by dougireton** [comment]
@sethvargo I'm working on a PR for this. Which version should I use for the `@since` on the `chocolatey_package` Matchers module - 4.6.0?

Here's an example for `WindowsPackageMatchers`

```ruby
module ChefSpec::API
  # @since 0.5.0
  module WindowsPackageMatchers
    ChefSpec.define_matcher :windows_package
<snip>
```

**Comment by sethvargo** [comment]
@dougireton awesome! The next version will be 4.6.0, since this is introducing a new API :smile: :heart:
