### ISSUE TITLE
Policyfile support is broken.

### ISSUE THREAD

**Issue by squaresurf** [sethvargo/chefspec#677]
Steps to reproduce:

* `chef generate cookbook test --policy`
* `cd test`
* `chef exec rspec`

The above will result with the following output:

```sh
  1) test::default When all attributes are default, on an unspecified platform converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Net::HTTPServerException: 412 "Precondition Failed "> with backtrace:
         # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
```

Please note I ran this with chefdk (0.11.2.) and chefspec (4.5.0).

Here are the contents of my `spec_helper.rb`:

```ruby
require 'chefspec'
require 'chefspec/policyfile'
```

Here are the contents of my `default_spec.rb`

```ruby
#
# Cookbook Name:: test
# Spec:: default
#
# Copyright (c) 2016 The Authors, All Rights Reserved.

require 'spec_helper'

describe 'test::default' do
  context 'When all attributes are default, on an unspecified platform' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
  end
end
```

**Comment by Poohblah** [comment]
@squaresurf, we've been running into this issue too.  Here's a fix my coworker suggests:

> Chefspec is breaking due to the rename of "cookbooks" to"cookbook_artifacts" in the chef zero export. It's already fixed in the latest git master of chefspec, but isn't available as a gem release yet.
>
> To fix in the mean time, edit `/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chefspec-4.5.0/lib/chefspec/policyfile.rb` and change the `::RSpec.configure` section near line 43 to:
>
> ```
>        ::RSpec.configure do |config|
>          config.cookbook_path = [
>            File.join(@tmpdir, 'cookbooks'),
>            File.join(@tmpdir, 'cookbook_artifacts')
>          ]
>        end
> ```

Hopefully there will be a release of chef-dk in the near future that includes this fix.

**Comment by Poohblah** [comment]
Looks like https://github.com/sethvargo/chefspec/pull/668 is the PR that fixed this issue.

**Comment by squaresurf** [comment]
Awesome! That fixed it for me. Thank you @Poohblah.

@sethvargo do you have any idea when this will be released?

**Comment by squaresurf** [comment]
Ok, so I figured out how to install chefspec master into my chefdk.

1. clone [sethvargo/chefspec](https://github.com/sethvargo/chefspec/)
1. cd into clone
1. `eval "$(chef shell-init bash)"`
1. rake install

Looking forward to this fix getting into chefdk since :point_up: is quite a bit to do for my co-workers to install the chefdk in order to work with our cookbooks.
