### ISSUE TITLE
subscribe_to(...).on(...) is misleading

### ISSUE THREAD

**Issue by Poohblah** [sethvargo/chefspec#678]
From the documentation:

> ### subscribes
> 
> Assert that a resource subscribes to another in the Chef run
> 
> ```
> resource = chef_run.service('apache2')
> expect(resource).to subscribe_to('template[/etc/foo]').on(:create).delayed
> ```

In this example, the wording makes it seem that we are testing that `service[apache2]` is being notified when `template[/etc/foo]` executes action `:create`.  However, what this example actually does is test that a notification is triggering `service[apache2]` to execute the action `:create` when the resource `template[/etc/foo]` is updated.

The error output from Chefspec makes this clear.  Here is an example from my own Chefspec run, where I am attempting to verify that the `execute[apache status]` resource is run after an apache reload:

```
     Failure/Error: expect(resource).to subscribe_to('service[apache2]').on(:reload).immediately
     
       expected "service[apache2]" to notify "execute[apache status]" with action :reload immediately, but did not.
     
       Other notifications were:
     
           "[service[apache2]]" notifies "execute[apache status]" to :run, :immediately
```

I think the example in the documentation should be updated to be a little more clear. For instance:

> ### subscribes
> 
> Assert that a resource subscribes to another in the Chef run
> 
> ```
> resource = chef_run.service('apache2')
> expect(resource).to subscribe_to('template[/etc/foo]').on(:restart).delayed
> ```

This would make more sense, since it's a little strange to "create" an apache2 service after a template is updated.  It's more likely that recipe authors would restart or reload the service instead.

Even better, perhaps it would be a good idea to add a new method as an alias to "on" in order to clarify the meaning of the method, for instance `to` (to align with the notify matcher) or `with_action` (which would be more accurate):

> ```
> resource = chef_run.service('apache2')
> expect(resource).to subscribe_to('template[/etc/foo]').with_action(:restart).delayed
> ```

**Comment by sethvargo** [comment]
Hi @Poohblah 

Notifications are typically confusing because of their inverse nature. For this reason, I would recommend using notifications instead of subscriptions.
