### ISSUE TITLE
Timeline for next gem release?

### ISSUE THREAD

**Issue by randomcamel** [sethvargo/chefspec#680]
Hi Seth:

We're prepping the next ChefDK release (for next week, I believe) and we would like to include https://github.com/sethvargo/chefspec/pull/668, along with all the other merged fixes and features.

Would it be possible for you to do a gem release this week? It'd be much appreciated, and make a big difference for Policyfile users.

Thanks,
Chris Doherty

(edit: Created https://github.com/sethvargo/chefspec/pull/681, modeled on the 4.5.0 PR.)

**Comment by sethvargo** [comment]
4.6.0 is out
