### ISSUE TITLE
Can't verifiy content of local templates 

### ISSUE THREAD

**Issue by joshrp** [sethvargo/chefspec#683]
I wanted to render a template from the file system (it's deployed with the application instead of inside the cookbook for reasons), I spent a long time thinking Chef was broken before I just tried it on a machine and it worked fine. It seems that the Renderer in ChefSpec cannot handle local templates, even if the path's resolve to the correct files.

This Resource does work fine on the actual machines.
```ruby
template '/var/www/secrets.json' do
  source /var/www/secrets.dist.erb'
  variables (item.to_hash)
  local true
end
```

And this spec passes fine, it verifies the path of the template being rendered.
```ruby
expect(chef_run).to render_file(absolute_path)
```

But trying to verify the contents fails:
```
expect(chef_run).to render_file(absolute_path).with_content{ |content|
     puts content
}
```
It doesn't know how to look for a local template:
``` 
Cookbook 'cookbook_name' does not contain a file at any of these locations:
         templates/chefspec-0.6.1//var/www/secrets.dist.erb
         templates/chefspec//var/www/secrets.dist.erb
         templates/default//var/www/secrets.dist.erb
         templates//var/www/secrets.dist.erb
```

I began digging into the code and comparing ChefSpec to Chef itself and it seems the 'local' option is missing from the templating but I'm not confident enough in Chef or Ruby to attempt a fix here.

**Comment by chilicheech** [comment]
I'm able to reproduce this error when I attempt to verify the content of a template of a cookbook that uses policyfiles. If I don't use policyfiles it works fine.

```
     RuntimeError:
       File templates/default/test.erb does not exist for cookbook test
```

**Comment by chilicheech** [comment]
Did a little debugging:
So, it’s looking for the file in a folder similar to:
`/var/folders/cp/vpqypqzn3c11k5j2y0thb0zm0013h4/T/d20160504-88244-7064ub/cookbook_artifacts/test/templates/default/test.erb`

The file is actually located at:
`/var/folders/cp/vpqypqzn3c11k5j2y0thb0zm0013h4/T/d20160504-88244-7064ub/cookbook_artifacts/test-b8d3630cc29ac15a2c57ba0c25259716b1e3b473/templates/default/test.erb`

It’s looking for it at the wrong spot.

**Comment by swimfrog** [comment]
+1

**Comment by Poohblah** [comment]
It looks like this is the actual issue:

https://github.com/chef/chef/issues/5089

**Comment by sethvargo** [comment]
Upstream
