### ISSUE TITLE
Add  Coverage.Table! to show more details about coverage

### ISSUE THREAD

**Issue by karcaw** [sethvargo/chefspec#685]
Can you add a Table formatted output to the Coverage Class to output more like this:

File:Line resource_name covered_flag

**Comment by sethvargo** [comment]
Hi @karcaw 

There was a long-term goal to allow people to specify their own templates (https://github.com/sethvargo/chefspec/blob/622a05b9f362f4219d0b89825d543518a9998ebf/lib/chefspec/coverage.rb#L124-L136), but never really took off. I would gladly review a PR to add this functionality, but I think the output should be JSON, not table format. If you want machine-parsable output, JSON is the best bet :smile:

**Comment by karcaw** [comment]
I don't want machine parse-able, just a list of all resources.  I'll work up a PR for you to review

**Comment by sethvargo** [comment]
Hi @karcaw 

It's very unlikely I will accept a PR to print things in table format just so they are "pretty". Everyone has a different style, and I think custom templates are a more realistic option in that case.
