### ISSUE TITLE
ChefSpec Encrypted Data Bag

### ISSUE THREAD

**Issue by sumitmathur** [sethvargo/chefspec#691]
Hi,

I am using encrypted data bags for my chef cookbook. The chef run need secret key during runtime and thus we are keeping secret on shared storage NFS mounted on all servers. Here is the code snippet 

```ruby
cache_dir = "#{node['example_app']['build_stage']}/key"      # So this path is actually on machine

#Loading the secret key from file /shared/appName/key/secret_key
secret = Chef::EncryptedDataBagItem.load_secret("#{cache_dir}/secret_key")

#This decrypts the data bag contents
priv_key = Chef::EncryptedDataBagItem.load("example_app", "passwords_properties", secret)
```

I want to write chef spec for the recipe that uses this. So i have create the path on my workstation with secrete key.  I have issue in reading the data bag items and using it . I am using the decrypted values in template file.

My data bag contains 2 items

```
{
   "id":"passwords_properties",
   "app.preprod.password":{
      "encrypted_data":"******",
      "iv":"*********",
      "version":1,
      "cipher":"aes-256-cbc"
   },
   "app.prod.password":{
      "encrypted_data":"*******",
      "iv":"*******",
      "version":1,
      "cipher":"aes-256-cbc"
   }
}
```

So when i read data bag in variable "priv_key" , will have 2 values .

I read following   https://github.com/sethvargo/chefspec/issues/248  &  https://github.com/sethvargo/chefspec/issues/249 . But not able to releate to my use case.  I am very new to chefspec and writing for first time.

**Comment by perobertson** [comment]
In your before block you can mock out what you expect to be returned when the encrypted data bag is loaded.

```
before do
  secret = Chef::EncryptedDataBagItem.load_secret("#{cache_dir}/secret_key")
  allow(Chef::EncryptedDataBagItem).to receive(:load).with('example_app', 'passwords_properties', secret).and_return({
    'passwords_properties' => {
      'app.preprod.password' => 'YOUR_PASSWORD',
      'app.prod.password' => 'YOUR_PASSWORD'
    }
  })
end
```
When your test reaches the line `priv_key = Chef::EncryptedDataBagItem.load("example_app", "passwords_properties", secret)`. `priv_key` will be set to the value that you mocked out in your before block.

The benefit of this is that you do not have to use the actual secret key in your tests as long as your code uses the same file in both your mocks and your recipe.

**Comment by madhatter** [comment]
Too bad there is no way to ignore the secret here at all. I get your idea, but using some cache_dir doesn't change the necessity to use the same file location in the recipe code.

**Comment by sethvargo** [comment]
https://github.com/sethvargo/chefspec/pull/733
