### ISSUE TITLE
Assert that the Chef run included a recipe from another cookbook

### ISSUE THREAD

**Issue by s0ph** [sethvargo/chefspec#698]
seth,
thank you for the amazing contribution!
there is [a post on stackoverflow](http://stackoverflow.com/questions/36650388/assert-that-the-chef-run-included-a-recipe-from-another-cookbook) that i am very interested to bring to your attention.

hope you will have the chance to look into it.

**Comment by sethvargo** [comment]
Hi @s0ph 

Thank you for opening an issue, however, please do not open issues that just point elsewhere on the Internet. They serve no value to someone visiting this issue from a Google search. If the OP on Stackoverflow has a question, the place to get help is on that forum of using the Chef mailing list. This issue tracker is primarily reserved for bug reports and feature requests. Thanks!
