### ISSUE TITLE
Multiple resources in the same recipe with the same name

### ISSUE THREAD

**Issue by watkinsv-hp** [sethvargo/chefspec#703]
When I have multiple resources named the same with different actions in the same recipe, I think ChefSpec is evaluating the current example against the last resource of that name in the chef run, so I can't test all of my recipe's resources. 

I understand the use case is a bit odd and that this may be more indicative of an improvement to the resource and provider or a nuance with how Chef parses the resources in a recipe, but it's worth running it by you to get your opinion as it pertains to ChefSpec. 

There's a demo of how to reproduce at https://github.com/watkinsv-hp/many_resources_same_name 

Thanks!

**Comment by sethvargo** [comment]
Yea, this is how ChefSpec works (more information is in the README). Resource names are how things are evaluated, so unfortunatlely ChefSpec may not work for your particular use case. Sorry!
