### ISSUE TITLE
Defining Runner in context causes cookbook not found error messages

### ISSUE THREAD

**Issue by ScOut3R** [sethvargo/chefspec#705]
Hi there,

I am using one cookbook though Berkshelf besides the local one. If I define the Runner in the context block then I receive a cookbook not found error for the included cookbook. I worked around this by moving the Runner initialisation in the before block, but I thought reporting this anyway.

Regards,
Mate

**Comment by sethvargo** [comment]
Hi @ScOut3R 

Could you please share your recipe and ChefSpec test?

**Comment by sethvargo** [comment]
Lack of activity
