### ISSUE TITLE
chef/platform/provider_priority_map LoadError on using Chef 12.9

### ISSUE THREAD

**Issue by logankoester** [sethvargo/chefspec#707]
Running `bundle exec rspec` throws this LoadError using `chef-12.9.41`. Locking to `chef-12.8.1` resolves this issue.

The [documentation for Chef::Platform::ProviderPriorityMap](http://www.rubydoc.info/github/opscode/chef/Chef/Platform/ProviderPriorityMap) states:

> This class is part of a private API. You should avoid using this class if possible, as it may be removed or be changed in the future.

It would seem that has happened! :grin:

**Comment by tas50** [comment]
@logankoester We're going to need additional information here. I'm not seeing this issue anywhere in our community cookbooks with the latest chefspec / chef releases. Can you provide more details on the cookbook you're testing and chefspec release.

**Comment by logankoester** [comment]
@tas50 Sorry, but after 8 months I'm afraid I don't remember anything about this. Since it didn't seem to be causing anyone else problems, let's close the issue.
