### ISSUE TITLE
upgrading chefdk to latest version breaks chefspec around data bags

### ISSUE THREAD

**Issue by kzw** [sethvargo/chefspec#715]
Not sure if this is chefspec or chef error.

I commit data bag items to the repo with the output from following command

`knife data bag show <bag> <item> -Fj`

With 12.9.41 this output is different from earlier versions such as 12.5 and 12.7.  Essentially there is an extra layer of dictionary in newer format and older data is wrapped in `raw-data` attribute in this outer dictionary.

chefspecs do not understand these data bags.  I had to manually edit newer data bags to be just like older formats for chefspecs to pass.

1)  when I have only 1 item in the bag
     `Chef::Exceptions::InvalidDataBagItemID:`
       Item pgbouncer-production-pass not found in data bag pgbouncer. Other items found:

2) When I have multiple items ithe bag
     `Chef::Exceptions::DuplicateDataBagItem:`
       Data bag 'pgbouncer' has items with the same name '' but different content.

My current chef version

```
chef --version
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3
```

**Comment by sethvargo** [comment]
Fixed in master
