### ISSUE TITLE
Matching options for resources with action :nothing

### ISSUE THREAD

**Issue by szymonpk** [sethvargo/chefspec#723]
It's common use case in our environment, we have chain of multiple resources with `action :nothing`, like shown below:

```ruby
execute "resource1" do
  command "command1"
  not_if { condition }
  notifies :run, "execute[resource2]"
end

execute "resource2" do
  command "command2"
  action :nothing
end

...
```

Sometimes `command2` is complex, computed from some node data and there is no way to test it out, because in test `.with` is ignored if I use `not_to` or `not_to`.

```ruby
it "creates execute" do
  expect(chef_run).to_not run_execute("resource2").with(command: "command2")
end
```

Any ideas or good practices how to handle this?

**Comment by joerg** [comment]
There actually is a build in rspec matcher which can be used

```
 it 'chef client is upgraded to pinned version' do
  chef_package = chef_run.package('chef')
  expect(chef_package).to do_nothing
  expect(chef_package).to have_attributes(version: '12.12.13-1.el6')
end
```

@sethvargo Since chef always calls them "properties" and not "attributes", maybe it would be a good idea to create and alias in the matchers, something like "alias :have_properties :have_attributes".

**Comment by szymonpk** [comment]
:heart: Thank you @joerg. I don't know how I've missed this.
