### ISSUE TITLE
Template rendering fails when cookbook_name != directory name

### ISSUE THREAD

**Issue by chuhn** [sethvargo/chefspec#725]
Hi,

I'm trying to test our cookbook on Travis, but it runs into errors like
`File templates/default/… does not exist for cookbook bla` 
cf. https://travis-ci.org/GSI-HPC/sys-chef-cookbook/builds/142703133

The reason seems to be that the git repo gets checked out to a directory called 'sys-chef-cookbook' while the cookbook's name is 'sys'.
The issue is easily reproducible locally with any cookbook containing template tests by renaming the cookbook dir.

I think the actual error is in [`get_filename` in Chef::Cookbook::FileSystemFileVendor](https://github.com/chef/chef/blob/master/lib/chef/cookbook/file_system_file_vendor.rb#L46-L55) which stupidly does a 
```ruby
File.join(basepath, @cookbook_name, filename)
```
Instead it should search all subdirs of `basepath` for a `metadata.rb` containing the right `name` attribute?

Are my findings correct? Is there a way to circumvent this problem on the chefspec side?

Cheers,
	Christopher

**Comment by chuhn** [comment]
Looks like I hit https://tickets.opscode.com/browse/CHEF-3307
Has been fixed by chef/chef@5713a002062c762e40e4378be6d7763eb3dd61a2 which got reverted by chef/chef@39f8848aac823bbd2c5186e0454da3a0fb8e8b0e

No fix within 3 years?

**Comment by sethvargo** [comment]
This is ChefSpec. Can you please open the issue on Chef? Thanks! 😄
