### ISSUE TITLE
Documentation: resource lookup matcher shouldn't be in "Writing Custom Matchers" section

### ISSUE THREAD

**Issue by iancward** [sethvargo/chefspec#727]
I just recently learned of the ability to create a matcher for looking up a custom resource from the resource collection (rather than having to troll the collection to find something), which is extremely useful for testing notifications on custom resources.
Unfortunately, this is in the "Writing Custom Matchers" section of the README, which details how to write custom matchers when consuming a cookbook that does not package natively.

For clarity's sake, this should probably be in a different section of the README, or should at least have some indication that it's probably good practice to package this in the cookbook that provides the resource, now that the feature is available.

**Comment by sethvargo** [comment]
I'd gladly review a PR for this change.
