### ISSUE TITLE
Chefspec incorrectly shows service as untouched when another spec fails

### ISSUE THREAD

**Issue by luckymike** [sethvargo/chefspec#728]
I have this in my recipe: 

```
service 'luigi' do
  action :start
end
```

and this in my spec:

```
expect(chef_run).to start_service('luigi')
```

With a failing spec (not the service spec) my coverage reports says the service isn't touched:

```
Untouched Resources:

  service[luigi]                     luigi_hired/recipes/conf.rb:50
```

With all specs passing, I get 100% coverage. 

I feel like this is an anomaly with `service` that I haven't seen with other resources.

**Comment by lamont-granquist** [comment]
@tas50 i can't replicate this and there isn't enough detail here to guess how to setup a repro case

**Comment by luckymike** [comment]
@tas50 @lamont-granquist I refactored the thing that failed significantly since this issue, so I can't easily provide an equivalent test case.

Since test coverage is [a metric of dubious value](https://coderanger.net/overtesting/), I'm fine with closing this. 

Perhaps if someone else encounters this, they'll find the issue and know they aren't alone, and can provide an example. If no one else does, then it's probably not worth the bandwidth to resolve anyway!
