### ISSUE TITLE
Deprecation warning for node.set

### ISSUE THREAD

**Issue by iancward** [sethvargo/chefspec#730]
I have chefspec 4.7.0 installed, and I'm getting Chef 14 deprecation warnings for `node.set`:
> WARN: node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence)

I updated my chefspec to use `chef_run.node.default` and it appears that the node attribute is not actually being set. Does chefspec support `node.default`?

Thanks.

**Comment by iancward** [comment]
FYI it appears that `node.normal` will work in the chefspec code; however, the warning is still printed.

**Comment by Xoph** [comment]
I am also seeing this issue.

When I use `node.set` in my ChefSpec tests to initialize attributes, I get both error # 1 and error # 2 as shown below.
When I use `node.override` in my ChefSpec tests to initialize attributes, I get only error # 2.

**Error # 1**
````
WARN: node.set is deprecated and will be removed in Chef 14, please use node.default/node.ov
erride (or node.normal only if you really need persistence)
````
**Error # 2**
````
WARN: "method access to node attributes (node.foo.bar) is deprecated and will be removed in
Chef 13, please use bracket syntax (node["foo"]["bar"])
```

Please advise what I should do to initialize node attributes properly in ChefSpec tests.

Thank you,
Christoph
GE Healthcare

**Comment by joelhandwell** [comment]
@sethvargo any thoughts? Getting same issue.

**Comment by sethvargo** [comment]
@tas50 what's the recommend way to set node attributes these days?

**Comment by tas50** [comment]
node.normal is the same thing as node.set and the name causes less confusion. Chefspec docs should get updated to not point people to node.set.

**Comment by joelhandwell** [comment]
I've changed from node.set to node.normal and getting ```WARN: method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"])``` as @Xoph got in **Error # 2** what is the right way to set custom attribute in chefspec without getting this warning?

**Comment by Xoph** [comment]
I still get that error as well. It seems to be internal Chef or some other cookbook dependency causing the error? But I'm not sure how to verify that.

**Comment by tas50** [comment]
Any chance you can post a gist of the chefspec run and the spec you believe is causing it?

**Comment by Xoph** [comment]
I tried to find the simplest recipe and test that would replicate this.
By the way, I have ChefDK 0.17.17 installed.

**test.rb:**
Empty File

**test_spec.rb:**
````
require 'chefspec'
require 'chefspec/berkshelf'

describe 'test::test' do
  context 'Test' do
    let(:chef_run) { ChefSpec::SoloRunner.new.converge(described_recipe) }

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
  end
end
````

**Comment by acoulton** [comment]
I was also seeing this including the `WARN: method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"])` that has also been reported here and a number of other warnings.

It appears to be related to the compat-resource cookbook - my cookbook depends on `apt`, which depends on that. When I commented out the apt cookbook from my berksfile the warnings all disappeared.

**Comment by zhaoteng0526** [comment]
Is there any limitation on OS. I got the same error and my platform is Win7

**Comment by coderanger** [comment]
@zhaoteng0526 Please don't comment on old, closed issues. If you think you have a new bug report, please file that so it can be discussed without notifying all these folks. Thanks.
