### ISSUE TITLE
Cacher does not consider example groups defined in a loop (with the same line number)

### ISSUE THREAD

**Issue by alecxvs** [sethvargo/chefspec#737]
I encountered a curious problem with my specs where I expected `cached( chef_run )` to cache my chef run for the example group, but it was caching it for multiple example groups.

Upon further investigation, I realized that the metadata location that it was using in keying the cache is based on file and line number and not location in the example group tree. Since some of my contexts are defined in a loop, they have the same line number, thus all have access to the same cached chef run.

Reproduction:
```Ruby
describe 'base example group' do
  ['redhat-7.2', 'debian-8.4', 'windows'].each do |platform|
    context "when #{platform}" do
      context 'when caching' do
        cached(:test_platform) { puts platform; platform }
        it 'should be the same platform' do
          expect(test_platform).to eq platform
        end
      end
    end
  end
end
```

**Comment by sethvargo** [comment]
Hi @alecxvs 

Thank you for opening an issue. You're correct that we cache off of the location RSpec provides. If you think there's a better key/value to cache on, please let me know. I'd be happy to review a PR - the code is in [cacher.rb](https://github.com/sethvargo/chefspec/blob/master/lib/chefspec/cacher.rb).
