### ISSUE TITLE
"Before" notification matcher modifier doesn't seem to work

### ISSUE THREAD

**Issue by davidcpell** [sethvargo/chefspec#743]
I'm trying to test that an `execute` resource notifies a `file` resource with the `:before` timer, but my unit test doesn't seem to recognize the notification at all when it's implemented with `:before`.

In the real code I have a guard clause in the `execute` resource and am doing some stubbing in the test, but for simplicity of illustrating the problem I've stripped down the test to this:
```
  context 'when it should notify' do 
    it 'notifies' do
      command = chef_run.execute('change-admin-user-password-from-default')
      expect(command).to notify('file[splunk-user-password-file]').before
    end
  end
```

And the stripped-down implementation:

```
execute 'change-admin-user-password-from-default' do
  command  "my_command"
  notifies :delete, 'file[splunk-user-password-file]', :before
end
```

Set up this way, the test raises a `NoMethodError`: 
`undefined method 'before' for #<ChefSpec::Matchers::NotificationsMatcher:0x7289b08>`

If I remove the `.before` modifier in the test, the test runs but fails, saying that there was no notification. If I change `:before` to `:immediately` in the implementation (again without the `.before` modifier), the test passes.

**Comment by tas50** [comment]
@davidcpell What version of ChefSpec are you running?

**Comment by davidcpell** [comment]
@tas50 sorry for not including this info before. Output of `chef -v` is:

ChefDK: 0.17.17
chef-client 12.13.37
delivery version: master
berks version: 4.3.5
kitchen version: 1.11.1

**Comment by tas50** [comment]
The before syntax support came out in ChefSpec 5.0, which we released yesterday. That will ship with the next ChefDK in a few weeks. Hang tight.

**Comment by davidcpell** [comment]
@tas50 thanks for pointing that out. What about just using the `notify` matcher without the `before` syntax at the end? I'm finding that ChefSpec isn't able to pick up on the notification at all, even without specifying the timer. Does the matcher default to looking for `:immediately`?
