### ISSUE TITLE
not_if File.exist? Stub

### ISSUE THREAD

**Issue by jsmickey** [sethvargo/chefspec#746]
The following recipe/spec works except if /opt/java/version exists on the workstation running rspec

I am using https://github.com/sethvargo/chefspec/issues/250 as a starting point.

Why is the local file being used?  If I change the spec to_not it passes.  What am I doing wrong?

```
**Recipe**
execute 'extract_jdk' do
  command 'tar --no-same-owner -xvf jdk.tar.gz -C /opt/java'
  not_if { ::File.exist?('/opt/java/version') }
end

**Spec**
it 'runs an execute to extract jdk' do
  allow(File).to receive(:exist?).and_call_original
  allow(File).to receive(:exist?).with('/opt/java/version').and_return(false)
  expect(chef_run).to run_execute('extract_jdk')
end

```

**Comment by sethvargo** [comment]
Are you sure it's not `exists?` and `exist`? Maybe you're namespacing the wrong file, try `::File` in the test.

You could also try switching those stubs (move and_call_original) to the bottom.

**Comment by jsmickey** [comment]
@sethvargo Thank you for the response

It is not ```exists?```, it is ```exist?```.  I double checked the code and rubocop is running with no errors.

I tried switching the stubs and added ::File.  But that did not fix it.

I tried a different execute resource with a not_if ::File.exist? and got the same error.  Once the file exists on my workstation, the test fails.  The stubs appear to be ignored.

I'm using ChefDK 0.17.17-1.  I was able to replicate the issue on a Jenkins instance with the same version of the ChefDK installed.

**Comment by jsmickey** [comment]
I was able to get this working.  I moved the allow assertions to a before block and was able to get the tests to pass

```
**Recipe**
execute 'extract_jdk' do
  command 'tar --no-same-owner -xvf jdk.tar.gz -C /opt/java'
  not_if { ::File.exist?('/opt/java/version') }
end

**Spec**
before do
  allow(File).to receive(:exist?).and_call_original
  allow(File).to receive(:exist?).with('/opt/java/version').and_return(false)
end

it 'runs an execute to extract jdk' do
  expect(chef_run).to run_execute('extract_jdk')
end
```
