### ISSUE TITLE
undefined method `periodic_apt_update' on chefspec 5.0.0

### ISSUE THREAD

**Issue by sandervanburken** [sethvargo/chefspec#748]
Testing a `apt_update` resource gives a 'undefined method' with chefspec 5.0.0.

To work around this add `depends 'apt'` to `metadata.rb`.

To reproduce the error, given this simple default recipe and spec file:

### `recipes/default.rb`
<pre>
# default recipe
apt_update 'system' do
  action :periodic
end
</pre>

### `spec/unit/recipes/default_spec.rb`
<pre>
# spec test for default recipe
require 'chefspec'

puts "### Version: #{ChefSpec::VERSION}"

RSpec.describe 'apttest::default' do
  context 'When on ubuntu 14.04' do
    let(:chef_run) do
      runner = ChefSpec::SoloRunner.new(platform: 'ubuntu', version: '14.04')
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end

    it 'updates apt' do
      expect(chef_run).to periodic_apt_update('system')
    end
  end
end
</pre>

### `rake spec` fails

<pre>
/opt/chefdk/embedded/bin/ruby -I/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-support-3.5.0/lib:/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
### Version: 5.0.0
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 25

apttest::default
  When on ubuntu 14.04
    updates apt (FAILED - 1)
    converges successfully

Failures:

  1) apttest::default When on ubuntu 14.04 updates apt
     Failure/Error: expect(chef_run).to periodic_apt_update('system')

     NoMethodError:
       undefined method `periodic_apt_update' for #<RSpec::ExampleGroups::ApttestDefault::WhenOnUbuntu1404:0x00000006ca5840>
     # ./spec/unit/recipes/default_spec.rb:22:in `block (3 levels) in <top (required)>'

Finished in 0.04667 seconds (files took 3.41 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/unit/recipes/default_spec.rb:21 # apttest::default When on ubuntu 14.04 updates apt

Randomized with seed 25

/opt/chefdk/embedded/bin/ruby -I/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-support-3.5.0/lib:/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
</pre>

**Comment by tas50** [comment]
I believe this is fixed on master and I'll be doing a 5.1 release shortly to get it out along with some other improvements. Feel free to open this up if you still see it happening with 5.1
