### ISSUE TITLE
apt-package fails to assert installing named arrays of package names

### ISSUE THREAD

**Issue by doertedev** [sethvargo/chefspec#768]
OHAI.

Chef:

``` ruby
apt_packages_to_install = [
  'asdf', 'asdf1', 'asdf2' 
]
apt_package 'tis but a description' do
  package_name apt_packages_to_install
  action :install
  only_if { %w(debian ubuntu).include? node['platform'] }
end
```

Spec (doesn't works but should):

``` ruby
    it 'on ubuntu' do
      chef_run = ChefSpec::ServerRunner.new(platform: 'ubuntu', version: '16.04').converge(described_recipe)
      expect(chef_run).to install_apt_package('apt-transport-https')
      expect(chef_run).to install_apt_package('ca-certificates')
    end
```

Spec (works but weird):

``` ruby
    it 'on ubuntu' do
      chef_run = ChefSpec::ServerRunner.new(platform: 'ubuntu', version: '16.04').converge(described_recipe)
      expect(chef_run).to install_apt_package(['apt-transport-https','ca-certificates'])
    end
```

This isn't tested [here](https://github.com/sethvargo/chefspec/blob/master/examples/apt_package/recipes/install.rb#L12). I assume I made something wrong?

Spec_helper.rb

``` ruby
require 'rspec'
require 'fauxhai'
require 'chefspec'

RSpec.configure do |config|
  config.formatter = 'progress'
  config.fail_fast = 1
  config.color = true
end
```

Using 3.5.3 on my Gentoo workstation (rbenv on 2.3.1)

**Comment by tas50** [comment]
The package name on a multi package install is in fact an array so this is correct. You won't be able to find each specific package because there's no resource with that package name. There's only a resource with ['apt-transport-https','ca-certificates']. This is working as intended even if it seems a bit odd.
