### ISSUE TITLE
Overwrite attributes containing hashes

### ISSUE THREAD

**Issue by merrykju** [sethvargo/chefspec#775]
Hi Seth,

when overwriting setting attributes it seems to me that this does not work with entire attribute hashes:

When monkey-debugging my recipe with

  puts "Attribute settings: #{node['nagios']['master']['macros']}"

an rspec run with

let(:chef_run) do 
  runner = ChefSpec::SoloRunner.new
  runner.node.normal['nagios']['master']['macros'] = {}
  runner.converge(described_recipe)
end   

shows that the attribute is not empty but instead returns the settings from the attributes file:

Attribute settings {"USER2"=>"/opt/nagios-plugins"}

How would you advise to test a chef run with an empty (or unset) attribute?

I'm using chefspec 5.2.0.

Thanks

   Patricia

**Comment by lamont-granquist** [comment]
@tas50 this is just doing a deep merge between default and normal attributes and is just 'how attributes work'

`node.default["nagios"]["master"]["macros"] = {}` might work, or `node.rm("nagios", "master", "macros")` plus setting a value.  although it seems a really weird use case.
