### ISSUE TITLE
stub lazy execution

### ISSUE THREAD

**Issue by chazzly** [sethvargo/chefspec#783]
There certainly may be a better approach to what i'm doing, but here what I've got.

I'm working on a jenkins wrapper cookbook.  In one portion, I go through a list of plug-ins to be installed and use the lwrp from the jenkins cookbook to do so:

```
node['jenkins']['plug_ins'].each do |p, v|
  jenkins_plugin p do
     Chef::Log.info("installing #{p} plugin")
     version v
     retries 1
     action :install
  end
end
``` 
These plugins must be installed and active for laters config changes to work, so jenkins needs to be restarted.  I could add a notify restart service['jenkins'] and set to :immediate, of course, but that means jenkins would get restarted with each and every plug-in, which could be dozens, especially on initial install.

So, I use a global variable as a flag, a ruby block to update that flag if (and only if) any of the plug-ins are installed, then test for that flag and do an immediate service restart:

```
$updt = false

ruby_block 'plug-in updt' do
  block { $updt = true }
  action :nothing
end

node['jenkins']['plug_ins'].each do |p, v|
  jenkins_plugin p do
     Chef::Log.info("installing #{p} plugin")
     version v[0]
     retries 1
     action :install
     notifies :run, 'ruby_block[plug-in updt]', :immediately if v[2]
  end
end

ruby_block 'immed restart' do
  block { puts 'restarting Jenkins....'}
  notifies :restart, 'service[jenkins]', :immediately
  notifies :run, 'ruby_block[sleeping]', :immediately
  only_if lazy { $updt }.to_s
end
```

the only_if for the restart ruby_block needs to be lazy because, the ruby_block to update $updt only fires after the notification during execution.

This all seems to work just fine on my nodes and test kitchen.  The problem is when I run rspec tests.  heres my spec:

```
  it 'installs plugins' do
    chef_run.node['jenkins']['plug_ins'].each do |p, v|
      expect(chef_run).to install_jenkins_plugin(p).with(version: v)
      pl = chef_run.jenkins_plugin(p)
      expect(pl).to notify('ruby_block[plug-in updt]').to(:run).immediately
    end
  end
```

When run, I get this error:
```
      ChefSpec::Error::CommandNotStubbed:
        Executing a real command is disabled. Unregistered command:

            command("#<Chef::DelayedEvaluator:0x007f810c7095d8@/var/folders/rg/14ns3__11vx1ghc_g747k3t40000gp/T/chefspec20161130-9692-1uxyflqfile_cache_path/cookbooks/new-jenkins/recipes/master.rb:75>")

        You can stub this command with:

            stub_command("#<Chef::DelayedEvaluator:0x007f810c7095d8@/var/folders/rg/14ns3__11vx1ghc_g747k3t40000gp/T/chefspec20161130-9692-1uxyflqfile_cache_path/cookbooks/new-jenkins/recipes/master.rb:75>").and_return(...)
```

I know how a normal command stub works, but I don't know how to stub a command that is going to change like this.  I've tried variations of: 
```
stub_command("#<Chef::DelayedEvaluator:*@/var/folders/rg/*/chefspec*/cookbooks/new-jenkins/recipes/master.rb:75>").and_return(true)
```
and
```
allow(Chef::DelayedEvaluator).to receive(:run).with('*/var/folders/rg/*/chefspec*/cookbooks/new-jenkins/recipes/master.rb:75').and_return(true)

```
with no luck.

Any suggestions?

**Comment by lamont-granquist** [comment]
You shouldn't need to lazy the `only_if`:

```ruby
flag = false

ruby_block "test" do
  block do
    flag = true
  end
end


log "flag is true" do
  level :warn
  only_if { flag }
end
```

at compile time that passes a block into only_if.  the ruby_block then executes and sets the flag to true, then the only_if is evaluated and is true:

```
% chef-client -z -r 'test::default'
[2017-04-18T07:30:59-07:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 13.0.118
resolving cookbooks for run list: ["test::default"]
Synchronizing Cookbooks:
  - test (0.0.1)
  - other_cookbook (0.0.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: test::default
  * ruby_block[test] action run
    - execute the ruby block test
  * log[flag is true] action write[2017-04-18T07:31:07-07:00] WARN: flag is true
[2017-04-18T07:31:07-07:00] WARN: flag is true



Running handlers:
Running handlers complete
Chef Client finished, 2/2 resources updated in 08 seconds
```

(and conveniently i seem to have a simple repro case of the double-logging bug in chef 13.0.x there as well...)

**Comment by chazzly** [comment]
That makes sense.  I ended up completely re-working this for an unrelated reason, I hadn't closed THIS because it still seemed like a legit question.

Thanks for the clarification.

**Comment by lamont-granquist** [comment]
we probably do have other bugs around legitimately using lazy and trying to use chefspec, but the best solution is to not lazy as much, its got all kinds of issues that i don't know how to generically fix and winds up in endless whack-a-mole land.
