### ISSUE TITLE
How to set 'platform' and 'platform_version' for centos?

### ISSUE THREAD

**Issue by maraaaa** [sethvargo/chefspec#798]
Hello,

How do you set `platform` and `platform_version` for CentOS or RHEL machines?

I have attempted to set `ChefSpec::ServerRunner.new(platform: 'centos', version: '7.3.1611')` according to `ohai platform` and `ohai platform_version` however, this returns the error `Fauxhai::Exception::InvalidPlatform: Could not find platform 'centos/7.3.1611' in any of the sources!`.  I have also tried a number of iterations of `version: '7', '7.*', ' 7*', '7.3', '7.3*'` and `platform: 'centos', 'CentOS', 'RHEL' 'rhel'`)  I've also tried wrapping the version in an array, `platform: ['centos'], version: ['7.3.1611']` to no avail.  It seems all of the examples in this repo set Ubuntu. 

At this point, I'm stumped.  What am I doing wrong?

Thanks!

```
[maraaaa@chef test]$ ohai platform_version
[
  "7.3.1611"
]
[maraaaa@chef test]$ ohai platform
[
  "centos"
]

##########################
# Create cookbook

[maraaaa@chef ~]$ chef generate cookbook test
Generating cookbook test
 - Ensuring correct cookbook file content
- Committing cookbook files to git
- Ensuring delivery configuration
- Ensuring correct delivery build cookbook content
- Adding delivery configuration to feature branch
- Adding build cookbook to feature branch
- Merging delivery content feature branch to master

Your cookbook is ready. Type `cd test` to enter it.

There are several commands you can run to get started locally developing and testing your cookbook.
Type `delivery local --help` to see a full list.

Why not start by writing a test? Tests for the default recipe are stored at:

test/smoke/default/default_test.rb

If you'd prefer to dive right in, the default recipe can be found at:

recipes/default.rb

[maraaaa@chef ~]$  cd test/
[maraaaa@chef test]$ ls
Berksfile  chefignore  metadata.rb  README.md  recipes  spec  test

##########################
# Run default tests, get warining

[maraaaa@chef test]$ rspec
WARNING: you must specify a platform and platform_version to your ChefSpec Runner and/or Fauxhai constructor, in the future omitting these will become a hard error
.

Finished in 4.01 seconds (files took 3.33 seconds to load)
1 example, 0 failures

##########################
# Attempt to set versiom, but get Invalid platform

[maraaaa@chef test]$ perl -pi -e "s/runner = ChefSpec::ServerRunner.new/runner = ChefSpec::ServerRunner.new\(platform: 'centos', version: '7.3.1611'\)/" spec/unit/recipes/default_spec.rb

[maraaaa@chef test]$ cat spec/unit/recipes/default_spec.rb
#
# Cookbook:: test
# Spec:: default
#
# Copyright:: 2017, The Authors, All Rights Reserved.

require 'spec_helper'

describe 'test::default' do
  context 'When all attributes are default, on an unspecified platform' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new(platform: 'centos', version: '7.3.1611')
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
  end
end

[maraaaa@chef test]$ rspec
F

Failures:

  1) test::default When all attributes are default, on an unspecified platform converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Fauxhai::Exception::InvalidPlatform: Could not find platform 'centos/7.3.1611' in any of the sources!> with backtrace:
         # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'

Finished in 0.37283 seconds (files took 6.81 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/unit/recipes/default_spec.rb:16 # test::default When all attributes are default, on an unspecified platform converges successfully
```

**Comment by maraaaa** [comment]
#765 seems to be doing effectively the same thing... using SoloRunner instead of ServerRunner (I'm assuming I'll be using search, hence the ServerRunner) and using the fat comma `'platform' => 'centos'` instead of the new hash syntax `platform: 'centos'`, but I get the same error using the fat comma, so I think the differences are stylistic only. (OFC: please correct me if I'm wrong!)

But he doesn't seem to be getting the same error...  I AM testing the cookbook on the same platform (different VM) that I'm writing the cookbook.

Also, setting:

```
runner = ChefSpec::ServerRunner.new(platform: 'ubuntu', version: '16.04')
````

resolves all errors... even running the rspec tests on a CentOS VM....

Also, setting:

```
      runner = ChefSpec::ServerRunner.new(platform: 'centos', version: '6.7')
```

So it seems to just be an issue with setting centos versions for 7.X?  I have to be missing something here...  What am I doing wrong please?

Thanks!

**Comment by ch4rms** [comment]
According to the fauxhai repo:
https://github.com/customink/fauxhai/tree/master/lib/fauxhai/platforms/centos

It looks like 7.3.1611 isn't included in the latest release (v3.10.0 at the time of this comment)
I came across this issue because my rspec tests were also blowing up.

ChefSpec::ServerRunner.new(platform: 'centos', version: '7.2.1511') worked for me

**Comment by sfromm-plm** [comment]
Thanks, **ch4rms**.  That worked for me, too.  Would still think that it would correctly parse "7.2", but this is fine for now.

**Comment by maraaaa** [comment]
Should it though? Technically, "7.2" isn't a valid CentOS/RHEL version
number since they switched numbering conventions.

How are older versions managed? Can I set a CentOS v "6.42"?

On Feb 15, 2017 05:50, "sfromm-plm" <notifications@github.com> wrote:

Thanks, *ch4rms*. That worked for me, too. Would still think that it would
correctly parse "7.2", but this is fine for now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sethvargo/chefspec/issues/798#issuecomment-280002417>,
or mute the thread

**Comment by sfromm-plm** [comment]
@maraaaa :  I think you're probably right.  Just logged into the box I'm writing this chef stuff for, and `redhat-release` says `7.2.1511`.

**Comment by lamont-granquist** [comment]
@tas50 you can probably close this, its certainly misfiled since it amounts to a request for additional fauxhai platforms in fauxhai
