### ISSUE TITLE
How to test edit_resource?

### ISSUE THREAD

**Issue by rmoriz** [sethvargo/chefspec#812]
Chef DSL's `edit_resource` should be test-able as well. see:

- https://coderanger.net/rewind/
- https://docs.chef.io/dsl_recipe.html#edit-resource

What do you think?

**Comment by lamont-granquist** [comment]
you gotta leave a more useful bug report.

AFAIK it should be testable.

there's bugs around use_inline_resources like #793 which need to get fixed or else a lot of the use cases for edit_resources will be broken, but that has nothing to do with edit_resources directly.

**Comment by rmoriz** [comment]
Okay, i'll try to provide a specific example:

```ruby
# cookbook1::default
file '/tmp/test' do
  content 'original content'
end


# cookbook2:default
edit_resource(:file, '/tmp/test') do
  content 'super new content'
end
```

the original file resource is easy testable, but how can i verify that `cookbook2::default` does the `edit_resource` right?

**Comment by lamont-granquist** [comment]
its exactly the same way.  look for the file resource on the resource collection to have gotten constructed with the 'super new content' content.

**Comment by lamont-granquist** [comment]
@tas50 i think this one is closable

**Comment by rmoriz** [comment]
Unless there is a way to test those resource modifications, this issue isn't resolved and chefspec just lacks a feature to do to that...

**Comment by lamont-granquist** [comment]
you don't test the implementation details.

testing this:

```ruby
file "/tmp/foo"

edit_resource(:file, "/tmp/foo") do
  content "foo"
end
```

is the same as testing this:

```ruby
file "/tmp/foo" do
  content "foo"
end
```

which in both cases is just this:

```ruby
  it 'should install zsh package' do
    expect(chef_run).to create_file('/tmp/foo').with(content: "foo")
  end
```

it doesn't matter if its written using edit_resource or not, what you're setting up expectations on is the final construction of the resource collection.  how you get there is irrelevant.

**Comment by olebel** [comment]
Recommended approach is to do not test library cookbook resources, excluding any library "include_recipe" appearances. 

Common pattern for using "edit_resource" is to edit resources that's defined in library, that we don't test.

Chefspec drop failures, when it meets edit_resource with template/file from library cookbook.

What's recommended way to use Chefspec in such situations?

**Comment by rmoriz** [comment]
@olebel why not?
