### ISSUE TITLE
do...end syntax with `with_content`?

### ISSUE THREAD

**Issue by atheiman** [sethvargo/chefspec#820]
In the readme, `{ ... }` notation is suggested for `.with_content` matcher block form.

```ruby
expect(chef_run).to render_file('/etc/foo').with_content { |content|
  # Regular RSpec matches work in here
  expect(content).to include('any RSpec matcher')
}
```

I just tried with `do ... end` syntax and am getting failures. Is this something with rspec Im finding? Im mostly just curious as I thought `{ ... }` and `do ... end` were synonymous in Ruby.

**Comment by lamont-granquist** [comment]
@tas50 could be closed as a better question to ask on stackoverflow, mailing list, slack.

**Comment by atheiman** [comment]
well if `{` is implemented somewhere, I think `do ... end` could be implemented as well

**Comment by lamont-granquist** [comment]
it is just ruby.  they're mostly synonymous except for when ruby gets confused about `{}` being ambiguous between a hash constructor and `do...end`

**Comment by atheiman** [comment]
Ahh i think it is actually the precedence difference between `{ ... }` and `do ... end` illustrated here: http://stackoverflow.com/a/5587403/3343740

I haven't confirmed this but I think:

```ruby
expect(chef_run).to(
  render_file('/etc/foo').with_content do |content|
  # Regular RSpec matches work in here
  expect(content).to include('any RSpec matcher')
end
```

**Comment by lamont-granquist** [comment]
yeah, that's the other thing i was trying to think of -- either way its just edge conditions of the ruby parser though and nothing chefspec can affect
