### ISSUE TITLE
Chefspec coverage display untouched resources of providers from another recipe

### ISSUE THREAD

**Issue by cvillalba** [sethvargo/chefspec#823]
Hi all 

I'm running a wrapper of icinga2 supermarket recipe and this wrapper uses some of its providers. 

My wrapper recipe using a provider from the community recipe looks like this:
```
icinga2_environment 'Name' do
  import node['icinga2']['server']['object']['host']['import']
  environment '_default'
  limit_region true
  host_display_name_attr 'fqdn'
end

```

My spec looks like this:
```
require 'spec_helper'

describe 'icinga2_wrapper::environment' do
  let(:chef_run) { ChefSpec::SoloRunner.new(LogLevel: :debug).converge(described_recipe) }

  before do
    allow_any_instance_of(Chef::Recipe).to receive(:icinga2_environment).and_call_original
    allow_any_instance_of(Chef::Recipe).to receive(:icinga2_environment).with('Name').and_return(true)
  end

  it 'should run icinga2_environment provider' do
    expect_any_instance_of(Chef::Recipe).to receive(:icinga2_environment)
    chef_run
  end

end
```

And the test coverage result looks something  like this:
 ```
rspec                         

icinga2_wrapper::environment
  should run icinga2_environment provider
.
.
.
ChefSpec Coverage report generated...

  Total Resources:   17
  Touched Resources: 7
  Touch Coverage:    41.18%

Untouched Resources:

  icinga2_environment[Name]   icinga2_wrapper/recipes/environment.rb:3
.
.
.
```

As you can see, the test passes but the coverage consider it as an untouched resource, and this happens with other recipes with same characteristics.  

My question is, can I exclude an specific provider from the coverage report (I'm using berkshelf btw)?, am I doing something wrong ?

I have tried to use the add_filter method shown here https://github.com/sethvargo/chefspec#reporting, but I've had no success.

Please, let me know if someone can help me with this issue.

Cheers

**Comment by lamont-granquist** [comment]
the `expect_any_instance_of(Chef::Recipe)` idiom is very wrong.  you need to be using something like `expect(chef_run).to create_icinga2_environment('Name')`  if there's no `create_icinga2_environment` matcher then you'll have to provide one or have the cookbook author provide one.

@tas50 this can also be closed.

**Comment by cvillalba** [comment]
thanks @lamont-granquist. I fixed my tests and I add matchers to make it work. Everything is fine now.
