### ISSUE TITLE
Chef encountered an error attempting to load the node data for "fauxhai.local"   and Failed to authenticate to the chef server (http 401).

### ISSUE THREAD

**Issue by chef1729** [sethvargo/chefspec#824]

**Comment by coderanger** [comment]
Any chance you have something like `Chef::Node.load(...)` in your cookbook code?

**Comment by chef1729** [comment]
Here is the complete log. I masked the organization url for safety purposes. And by the way some of our cookbooks work and some fail. I am building a new server clone of another jenkins machine. Our previous all cookbooks converge and work but not on this one.

================================================================================
Chef encountered an error attempting to load the node data for "fauxhai.local"
================================================================================

Authentication Error:
---------------------
Failed to authenticate to the chef server (http 401).

Server Response:
----------------


Relevant Config Settings:
-------------------------
chef_server_url   "https://xxxxxxxxxx"
node_name         "fauxhai.local"
client_key        ""

If these settings are correct, your client_key may be invalid, or
you may have a chef user with the same client name as this node.

Platform:
---------
x86_64-linux

  example at ./spec/recipes/users_spec.rb:18 (FAILED - 1)

================================================================================
Chef encountered an error attempting to load the node data for "fauxhai.local"
================================================================================

Authentication Error:
---------------------
Failed to authenticate to the chef server (http 401).

**Comment by lamont-granquist** [comment]
@tas50 too vague to be actionable, can close this

**Comment by jpSimkins** [comment]
I too am having [this issue](https://github.com/chef-cookbooks/chef-client/issues/464#issuecomment-299618192) and this seems related to another ticket https://github.com/chef-cookbooks/chef-client/issues/464
