### ISSUE TITLE
Support for roles?

### ISSUE THREAD

**Issue by emanuelez** [sethvargo/chefspec#98]
In one of my cookbooks I have something like this:

``` ruby
if node.run_list.roles.include? node['gerrit']['dbrole']
  # Do Stuff
else
  Chef::Log.error "External databases not supported yet by this recipe"
end
```

and I try to test it with:

``` ruby
let(:chef_run) {
  runner = ChefSpec::ChefRunner.new(platform:'ubuntu', version:'12.04') do |node|
    node.set['cpu'] = {'total' => 1}
  end
  runner.converge 'role[database]', 'gerrit::default'
  runner
 }
```

But this runs into:

```
Failure/Error: runner.converge 'role[database]', 'gerrit::default'
     Chef::Exceptions::MissingRole:
       The expanded run list includes nonexistent roles: database
```

Is there a better way to do this?

**Comment by yanefski** [comment]
Hi @lonniev , i having exactly the same issue as you have described using Chef-solo to provision a windows VM via Vagrant.  Recipes run great on Windows when my chef.run_list is full of recipes, but moving these recipes to a Role and putting chef.add_role("foo") in my Vagrant file I get the same missing role error you note above.  I check on the VM and can see that the defined Role (.json) is indeed copied over.  Wondering if you made any progress or I can put myself on the watchlist for the issue you created.  Thanks!  John

**Comment by lonniev** [comment]
To work around this, I add the following to the Vagrantfile in the chef provisioner block:




```ruby


    vmh.vm.provision "chef_solo" do |chef|




      chef.log_level = :warn

      

      chef.custom_config_path = "ChefConfig.WindowsMonkeyPatch"




      chef.cookbooks_path = "./cookbooks"

      chef.roles_path = ["./roles"]

      chef.data_bags_path = "./bags”

```




Then, in the ChefConfig.WindowsMonkeyPatch file (in the same directory as the Vagrantfile) I add this line:




```ruby

role_path "c:/vagrant/roles"


```



The actual value for role_path has to match the location of where Vagrant, Chef, and Virtualbox actually map the host’s `roles` directory to the one within the guest.

**Comment by lonniev** [comment]
To work around this, I add the following to the Vagrantfile in the chef provisioner block:

```ruby

    vmh.vm.provision “chef_solo” do |chef|

      chef.log_level = :warn

      chef.custom_config_path = “ChefConfig.WindowsMonkeyPatch”

      chef.cookbooks_path = “./cookbooks”
      chef.roles_path = [“./roles”]
      chef.data_bags_path = “./bags”
```

Then, in the ChefConfig.WindowsMonkeyPatch file (in the same directory as the Vagrantfile) I add this line:

```ruby
role_path “c:/vagrant/roles”
```
The actual value for role_path has to match the location of where Vagrant, Chef, and Virtualbox actually map the host’s `roles` directory to the one within the guest.

**Comment by yanefski** [comment]
Thanks Lonnie for the details.  C:/vagrant on my VM is a mount to the chef-solo working directory on my mac and has the /roles subfolder, but the error is the same even with setting the custom_config_path.  What version of Virtual Box are you using?  Thanks again!  John

**Comment by lonniev** [comment]
I am running VB 4.3.20 and have the 4.3.20 guest additions on the host and in the guests.


—Lonnie VanZandt

303-900-3048

**Comment by yanefski** [comment]
Okay, I'm running 4.3.20 too, and my VM is windows server 2012 R2 that I added the guest additions to before creating my own 2012r2.box file.  Hmmm..... will keep digging here.  Thanks again for your help.  I'll update the thread if I figure out the issue on my end!  John

**Comment by yanefski** [comment]
One more question Lonnie - what version of Chef are you downloading to your new VM?  My vagrant file is configured to grab 'latest" which is Chef Omnibus 12.0.3.  If you are having success pinned to an earlier version I'd be willing to give that a try.  Thanks again!!  John

**Comment by lonniev** [comment]
12.0.3 as well. Regrets.


—Lonnie VanZandt

303-900-3048

**Comment by yeungs** [comment]
I found also found for Windows (don't be a hater) chef-client 11.18.3 still works.
